/*******************************************************************************
 * Copyright 2009, 2017 Martin Davis
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * This file was semi-automatically converted from the public-domain USGS PROJ source.
 */
package org.locationtech.proj4j.proj;

import org.locationtech.proj4j.InvalidValueException;
import org.locationtech.proj4j.ProjCoordinate;
import org.locationtech.proj4j.ProjectionException;
import org.locationtech.proj4j.util.ProjectionMath;

public class GaussProjection extends Projection {

	private static final long serialVersionUID = 4713313535538578370L;

	private final static int MAX_ITER = 20;
	private final static double DEL_TOL = 1.0e-14;

  private double C;
  private double K;
//  private double e;
  protected double rc;
  protected double phic0;
  private double ratexp;

	public GaussProjection() {
	}

	public ProjCoordinate project(double x, double y, ProjCoordinate out) {
    out.y = 2.0 * Math.atan( K * Math.pow(Math.tan(0.5 * y + ProjectionMath.QUARTERPI), this.C) * srat(this.e * Math.sin(y), this.ratexp) ) - ProjectionMath.HALFPI;
    out.x = C * x;
    return out;
	}

	public ProjCoordinate projectInverse(double x, double y, ProjCoordinate out) {
    double lon = x / this.C;
    double lat = y;
    double num = Math.pow(Math.tan(0.5 * lat + ProjectionMath.QUARTERPI)/this.K, 1./this.C);
    int i;
    for (i = MAX_ITER; i > 0; --i) {
      lat = 2.0 * Math.atan(num * srat(this.e * Math.sin(y), -0.5 * this.e)) - ProjectionMath.HALFPI;
      if (Math.abs(lat - y) < DEL_TOL) break;
      y = lat;
    } 
    /* convergence failed */
    if (i <= 0) {
      throw new ProjectionException(this, ProjectionException.ERR_17);
    }
    out.x = lon;
    out.y = lat;
		return out;
	}

	/**
	 * {@code pj_gauss_ini} ({@code 9.8.1:src/gauss.cpp:49-79}).
	 * <p>
	 * <b>The {@code lat_0 = ±90} branch was missing.</b> Upstream tests
	 * {@code .5*phi0 + M_FORTPI &lt; 1e-10} — true only at the south pole, where
	 * {@code tan(.5*phi0 + pi/4)} is exactly 0 — and takes {@code K = 1/srat} rather than dividing
	 * by that zero. Without it {@code K} is {@code Infinity} and every coordinate comes back
	 * non-finite: {@code builtins.gie}'s four {@code +proj=sterea +ellps=GRS80 +lat_0=-90} rows
	 * measured exactly that.
	 * <p>
	 * Upstream also returns {@code nullptr} — a definition rejection — when {@code C} or the
	 * {@code srat} factor is 0, which are the two other ways the expression can degenerate.
	 * <p>
	 * The 20-trip {@code pow} loop in {@link #projectInverse} is reproduced, not improved: PROJ
	 * 9.8.1 still solves the inverse conformal latitude that way behind {@code sterea}, and the
	 * corpus's expected values were generated by it.
	 *
	 * @throws org.locationtech.proj4j.InvalidValueException where upstream returns
	 *         {@code nullptr} from {@code pj_gauss_ini}
	 */
	public void initialize() {
		super.initialize();
    double sphi = Math.sin(projectionLatitude);
    double cphi = Math.cos(projectionLatitude);
    cphi *= cphi;
    rc = Math.sqrt(1.0 - es) / (1.0 - es * sphi * sphi);
    C = Math.sqrt(1.0 + es * cphi * cphi / (1.0 - es));
    if (C == 0.0) {
      throw new InvalidValueException(
          "Invalid ellipsoid for the Gauss conformal sphere: the cone constant C is 0 at lat_0 = "
              + Math.toDegrees(projectionLatitude) + " degrees");
    }
    phic0 = ProjectionMath.asinChecked(sphi / C);
    ratexp = 0.5 * C * e;
    double sratValue = srat(e * sphi, ratexp);
    if (sratValue == 0.0) {
      throw new InvalidValueException(
          "Invalid ellipsoid for the Gauss conformal sphere: the eccentricity factor is 0 at "
              + "lat_0 = " + Math.toDegrees(projectionLatitude) + " degrees");
    }
    if (0.5 * projectionLatitude + ProjectionMath.QUARTERPI < 1e-10) {
      // gauss.cpp:71-72. lat_0 = -90 exactly: tan(.5*phi0 + pi/4) is 0, so the general expression
      // divides by zero. Upstream substitutes the limit.
      K = 1.0 / sratValue;
    } else {
      K = Math.tan(0.5 * phic0 + ProjectionMath.QUARTERPI)
          / (Math.pow(Math.tan(0.5 * projectionLatitude + ProjectionMath.QUARTERPI), this.C)
              * sratValue);
    }
	}

  private static double srat(double esinp, double exp) {
    return Math.pow((1.0 - esinp) / (1.0 + esinp), exp);
}

	public boolean hasInverse() {
		return true;
	}

	public String toString() {
		return "Gauss";
	}

}

