/*
 * Copyright 2026 The Proj4J Contributors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.locationtech.proj4j.pipeline;

import java.io.IOException;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

import org.locationtech.proj4j.CrsTransformException;
import org.locationtech.proj4j.ErrorCause;
import org.locationtech.proj4j.Registry;
import org.locationtech.proj4j.datum.VerticalGrid;
import org.locationtech.proj4j.gie.GieIoUnits;

/**
 * {@code +proj=deformation} — kinematic datum shifting through a velocity model,
 * ported from {@code 9.8.1:src/transformations/deformation.cpp}.
 *
 * <h2>The operation</h2>
 *
 * <pre>
 * X_out = X_in + (t_obs - t_epoch) * DX
 * Y_out = Y_in + (t_obs - t_epoch) * DY
 * Z_out = Z_in + (t_obs - t_epoch) * DZ
 * </pre>
 *
 * <p>Input and output are <b>geocentric cartesian metres</b> ({@code P-&gt;left} and
 * {@code P-&gt;right} are both {@code PJ_IO_UNITS_CARTESIAN}), which is why the corpus
 * always writes it between two {@code +proj=cart} steps. The grid, however, is
 * indexed geographically and its three channels are east, north and up — so every
 * evaluation converts cartesian to geodetic to find the cell, reads an ENU velocity
 * triple, and rotates that triple back into the cartesian frame.
 *
 * <h2>The two grid spellings</h2>
 *
 * <p>A modern model is one three-channel Geodetic TIFF Grid named by {@code +grids}.
 * The historical spelling is a pair: {@code +xy_grids} in CTable/CTable2 (or NTv1 or
 * NTv2) form for east and north, and {@code +z_grids} in GTX form for up. Both
 * spellings expect <b>millimetres per year</b>, which is why every channel is divided
 * by 1000 on the way out.
 *
 * <p>{@code +grids} is refused here with a message naming the reason, because proj4j
 * has no GeoTIFF grid reader: the three-channel form cannot be read at all, and the
 * two-grid form covers everything the corpus exercises with a legacy grid.
 *
 * <h2>{@code +dt} versus {@code +t_epoch}, which are mutually exclusive</h2>
 *
 * <p>Exactly one must be given ({@code deformation.cpp:377-392}). With {@code +dt} the
 * interval is fixed and the coordinate's own epoch is never read. With
 * {@code +t_epoch} the interval is {@code t - t_epoch}, and a coordinate whose
 * {@code t} is {@code HUGE_VAL} — gie's spelling for "no epoch" — is
 * {@code PROJ_ERR_COORD_TRANSFM_MISSING_TIME}. Note that gie zero-fills an unwritten
 * fourth ordinate, so "no epoch" has to be written out as the literal
 * {@code HUGE_VAL}; a three-ordinate row arrives with {@code t = 0} and is a perfectly
 * valid observation at year zero.
 *
 * <p>{@code +t_obs} is a <b>hard error</b> with a migration message
 * ({@code deformation.cpp:400}), not a synonym for {@code +dt}. It is undocumented and
 * one of the entries in this project's "implement from the code, not the docs" table.
 *
 * <h2>The inverse is iterative and its z is not</h2>
 *
 * <p>{@code pj_deformation_reverse_shift} runs a 10-iteration fixed point on the
 * horizontal components with a {@code 1e-8} tolerance on {@code hypot(dif.x, dif.y)},
 * carrying z along only because the cartesian-to-geodetic conversion needs it, and
 * then <b>overwrites</b> z with the one-step value {@code input.z - dt * z0} computed
 * from the <em>first</em> evaluation. Ported verbatim, including that overwrite: the
 * expected values in {@code deformation.gie} were generated by it, and "improving" the
 * z iteration would change them.
 *
 * <p>Note also that the loop's {@code dif.z} uses {@code out.z - dt * delta.z} where
 * the other two use {@code + dt * delta}. That asymmetry is upstream's, and it is
 * inside the discarded part of the computation, so it has no effect on the result — it
 * is transcribed rather than tidied so the two files can be diffed.
 *
 * <p>Immutable after construction; safe to share.
 *
 * @since 1.5
 */
final class DeformationOperator implements PipelineOperator {

    /** {@code #define TOL 1e-8} on {@code hypot(dif.x, dif.y)}. */
    private static final double TOL = 1e-8;

    /** {@code #define MAX_ITERATIONS 10}. */
    private static final int MAX_ITERATIONS = 10;

    private final CartConversion cart;
    private final HorizontalGrids hgrids;
    private final List<VerticalGrid> vgrids;
    private final double dt;
    private final double tEpoch;
    private final String description;

    /**
     * @param registry resolves {@code +ellps=}
     * @param params   the step's fully expanded parameter list
     */
    DeformationOperator(final Registry registry, final ProjParams params) {
        final boolean hasXy = params.has("xy_grids");
        final boolean hasZ = params.has("z_grids");
        final boolean hasGrids = params.has("grids");

        // deformation.cpp:352-357. Note the shape of the test: +grids alone is enough,
        // otherwise BOTH of the pair are required.
        if (!hasGrids && (!hasXy || !hasZ)) {
            throw new PipelineDefinitionException(PipelineErrorCode.MISSING_ARG,
                    "Either +grids or (+xy_grids and +z_grids) should be specified.");
        }
        if (hasGrids) {
            throw new PipelineDefinitionException(PipelineErrorCode.NOT_IMPLEMENTED_HERE,
                    "+proj=deformation +grids=" + params.value("grids")
                            + ": the single-file form is a three-channel Geodetic TIFF Grid, and "
                            + "proj4j has no GeoTIFF grid reader. Use the historical "
                            + "+xy_grids= (CTable2/NTv1/NTv2) and +z_grids= (GTX) pair.");
        }

        this.hgrids = HorizontalGrids.open(params.value("xy_grids"), "xy_grids");
        this.vgrids = openVerticalGrids(params.value("z_grids"));

        // deformation.cpp:394-411. HUGE_VAL is the "unset" sentinel for both, and
        // exactly one of them must end up set.
        final boolean hasDt = params.has("dt");
        final boolean hasTEpoch = params.has("t_epoch");
        if (params.has("t_obs")) {
            throw new PipelineDefinitionException(PipelineErrorCode.MISSING_ARG,
                    "+t_obs parameter is deprecated. Use +dt instead.");
        }
        if (!hasDt && !hasTEpoch) {
            throw new PipelineDefinitionException(PipelineErrorCode.MISSING_ARG,
                    "either +dt or +t_epoch needs to be set.");
        }
        if (hasDt && hasTEpoch) {
            throw new PipelineDefinitionException(PipelineErrorCode.MUTUALLY_EXCLUSIVE_ARGS,
                    "+dt or +t_epoch are mutually exclusive.");
        }
        this.dt = hasDt ? params.doubleValue("dt", Double.NaN) : Double.POSITIVE_INFINITY;
        this.tEpoch = hasTEpoch ? params.doubleValue("t_epoch", Double.NaN)
                : Double.POSITIVE_INFINITY;

        final double[] ellipsoid = StepEllipsoid.resolve(registry, params);
        this.cart = new CartConversion(ellipsoid[0], ellipsoid[1]);

        this.description = "deformation xy_grids=" + params.value("xy_grids")
                + " z_grids=" + params.value("z_grids")
                + (hasDt ? " dt=" + dt : " t_epoch=" + tEpoch);
    }

    /**
     * {@code pj_vgrid_init} ({@code grids.cpp:3753}) — same {@code @}-optional rule as
     * the horizontal list, and the same refusal for a required grid that is absent.
     */
    private static List<VerticalGrid> openVerticalGrids(final String spec) {
        if (spec == null || spec.isEmpty()) {
            throw new PipelineDefinitionException(PipelineErrorCode.MISSING_ARG,
                    "+z_grids parameter missing.");
        }
        try {
            return Collections.unmodifiableList(
                    new ArrayList<VerticalGrid>(VerticalGrid.fromGeoidGrids(spec)));
        } catch (final IOException e) {
            throw new PipelineDefinitionException(PipelineErrorCode.FILE_NOT_FOUND_OR_INVALID,
                    "+z_grids=" + spec + ": could not find requested z_grid(s): "
                            + e.getMessage(), e);
        }
    }

    /** {@code P-&gt;left = PJ_IO_UNITS_CARTESIAN} ({@code deformation.cpp:420}). */
    @Override
    public GieIoUnits declaredLeft() {
        return GieIoUnits.CARTESIAN;
    }

    /** {@code P-&gt;right = PJ_IO_UNITS_CARTESIAN} ({@code deformation.cpp:421}). */
    @Override
    public GieIoUnits declaredRight() {
        return GieIoUnits.CARTESIAN;
    }

    /** Never called: neither declared side is {@link GieIoUnits#WHATEVER}. */
    @Override
    public void overrideUnits(final GieIoUnits left, final GieIoUnits right) {
        // no-op, deliberately
    }

    /** {@code pj_deformation_forward_4d}. */
    @Override
    public void forward(final double[] coord) {
        final double interval = interval(coord[3]);
        final double[] shift = gridShift(coord[0], coord[1], coord[2]);
        coord[0] += interval * shift[0];
        coord[1] += interval * shift[1];
        coord[2] += interval * shift[2];
    }

    /** {@code pj_deformation_reverse_4d}. */
    @Override
    public void inverse(final double[] coord) {
        final double interval = interval(coord[3]);
        reverseShift(coord, interval);
    }

    /**
     * {@code pj_deformation_forward_4d:262-273}. With {@code +dt} the coordinate's
     * epoch is never read at all; with {@code +t_epoch} a {@code HUGE_VAL} epoch is
     * {@code PROJ_ERR_COORD_TRANSFM_MISSING_TIME}.
     */
    private double interval(final double t) {
        if (!Double.isInfinite(dt)) {
            return dt;
        }
        if (Double.isInfinite(t) || Double.isNaN(t)) {
            throw new CrsTransformException(ErrorCause.MISSING_TIME,
                    "+proj=deformation +t_epoch=" + tEpoch + " needs the coordinate's own epoch, "
                            + "and this coordinate has none");
        }
        return t - tEpoch;
    }

    /**
     * {@code pj_deformation_get_grid_shift} ({@code deformation.cpp:139-196}): the ENU
     * velocity triple at this position, rotated into the cartesian frame, in metres per
     * year.
     *
     * <p>Upstream calls {@code proj_errno_restore} at the end, which <b>discards</b> an
     * {@code OUTSIDE_GRID} raised by the grid read and leaves the caller to notice that
     * the returned components are {@code HUGE_VAL}. Since the ENU-to-cartesian rotation
     * mixes {@code +HUGE_VAL} and {@code -HUGE_VAL}, what actually reaches the caller is
     * a mixture of infinities and {@code NaN}, and upstream's
     * {@code if (shift.x == HUGE_VAL)} test does not reliably catch it — the coordinate
     * comes out {@code NaN}. Both PROJ and proj4j therefore report a failure for such a
     * row (upstream by producing a non-finite coordinate, which is what
     * {@code deformation.gie}'s two {@code expect failure errno
     * coord_transfm_outside_grid} rows assert); the difference is only that proj4j says
     * which grid and where, and that a finite input can never leave here as a plausible
     * coordinate.
     *
     * @return {@code {DX, DY, DZ}} in metres per year
     */
    private double[] gridShift(final double x, final double y, final double z) {
        final double[] geodetic = {x, y, z, 0.0};
        cart.inverse(geodetic);
        final double lam = geodetic[0];
        final double phi = geodetic[1];

        final double[] hv = hgrids.value(lam, phi);
        final double up = verticalValue(lam, phi);

        // "grid values are stored as mm/yr, we need m/yr"
        final double e = hv[0] / 1000.0;
        final double n = hv[1] / 1000.0;
        final double u = up / 1000.0;

        final double sp = Math.sin(phi);
        final double cp = Math.cos(phi);
        final double sl = Math.sin(lam);
        final double cl = Math.cos(lam);

        // ENU -> PJ_XYZ, per Noerbech et al. 2003 as cited by deformation.cpp:180-188.
        return new double[] {
            -sp * cl * n - sl * e + cp * cl * u,
            -sp * sl * n + cl * e + cp * sl * u,
            cp * n + sp * u,
        };
    }

    /** {@code pj_vgrid_value(P, Q-&gt;vgrids, lp, 1.0)} — multiplier 1, not vgridshift's -1. */
    private double verticalValue(final double lam, final double phi) {
        if (vgrids.isEmpty()) {
            return 0.0;
        }
        if (Double.isNaN(lam) || Double.isNaN(phi)) {
            return Double.NaN;
        }
        for (int i = 0; i < vgrids.size(); i++) {
            final VerticalGrid grid = vgrids.get(i);
            if (!grid.covers(lam, phi)) {
                continue;
            }
            final double value = grid.valueAt(lam, phi, 1.0);
            if (Double.isNaN(value)) {
                throw new CrsTransformException(ErrorCause.GRID_NODATA,
                        "every node surrounding (" + Math.toDegrees(lam) + ", "
                                + Math.toDegrees(phi) + ") in +z_grids grid "
                                + grid.getGridName() + " is nodata");
            }
            return value;
        }
        throw new CrsTransformException(ErrorCause.COORDINATE_OUTSIDE_GRID,
                "(" + Math.toDegrees(lam) + ", " + Math.toDegrees(phi)
                        + ") is outside every grid of +z_grids");
    }

    /**
     * {@code pj_deformation_reverse_shift} ({@code deformation.cpp:199-241}), verbatim.
     *
     * @param coord    {@code {X, Y, Z, t}}, mutated in place
     * @param interval the signed number of years
     */
    private void reverseShift(final double[] coord, final double interval) {
        final double inputX = coord[0];
        final double inputY = coord[1];
        final double inputZ = coord[2];

        double[] delta = gridShift(inputX, inputY, inputZ);
        final double z0 = delta[2];

        double outX = inputX - interval * delta[0];
        double outY = inputY - interval * delta[1];
        double outZ = inputZ + interval * delta[2];

        int i = MAX_ITERATIONS;
        double difX;
        double difY;
        double difZ;
        do {
            delta = gridShift(outX, outY, outZ);

            difX = outX + interval * delta[0] - inputX;
            difY = outY + interval * delta[1] - inputY;
            difZ = outZ - interval * delta[2] - inputZ;
            outX += difX;
            outY += difY;
            outZ += difZ;
        } while (--i > 0 && Math.hypot(difX, difY) > TOL);

        // Upstream's overwrite: the iterated z is discarded and replaced with the
        // one-step value from the FIRST grid evaluation. Deliberate, and load bearing
        // for every expected value in deformation.gie.
        coord[0] = outX;
        coord[1] = outY;
        coord[2] = inputZ - interval * z0;
    }

    @Override
    public boolean hasInverse() {
        return true;
    }

    @Override
    public String description() {
        return description;
    }

    @Override
    public String toString() {
        return "DeformationOperator[" + description + "]";
    }
}
