/*******************************************************************************
 * Copyright 2026
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *******************************************************************************/

package org.locationtech.proj4j.determinism;

import java.util.ArrayList;
import java.util.List;
import java.util.Random;

/**
 * The probe arguments for the {@code StrictMath} golden table, generated by code rather than
 * checked in.
 *
 * <p>Deliberate: the generator
 * ({@link GenerateStrictMathGoldenTable}) and the assertion
 * ({@link StrictMathGoldenTableTest}) both call into here, so the committed golden's
 * <em>arguments</em> can never drift from the arguments the test evaluates. Only the
 * <em>results</em> are committed. If the two lists could drift, a golden file would silently
 * describe inputs nobody tests any more, and the test would pass while measuring nothing.
 *
 * <p>Every list is a pure function of constants and fixed-seed {@link Random} streams, so it is
 * identical on every JVM and every architecture. That property is load-bearing: the whole point of
 * the golden is that an x86-64 leg and an AArch64 leg evaluate the same arguments.
 *
 * <h2>Why these arguments</h2>
 *
 * <p>A random sweep alone is a poor test of a transcendental, because the interesting behaviour is
 * concentrated at branch boundaries that random sampling essentially never hits. The probe set is
 * therefore three-layered:
 *
 * <ol>
 *   <li><b>The real workload.</b> Latitudes and longitudes in radians on whole and fractional
 *       degrees, eccentricity-scale quantities for the ellipsoids proj4j ships, and the
 *       conformal/authalic-latitude intermediates. This is what proj4j actually evaluates.</li>
 *   <li><b>Branch boundaries.</b> Every {@code k*pi/4} with immediate {@code nextUp}/{@code
 *       nextDown} neighbours (argument reduction), the fdlibm kernel thresholds
 *       ({@code 2^-27}, {@code 2^-28}, {@code 2^19*(pi/2)}), the {@code log}/{@code log1p}
 *       poly-vs-table split near 1, {@code pow}'s special-value fast paths, and the domain edges of
 *       {@code asin}/{@code acos}.</li>
 *   <li><b>Special values.</b> Signed zero, both infinities, NaN. These are compared on raw bits,
 *       so {@code -0.0} is distinguished from {@code +0.0} - a real distinction at the equator and
 *       the antimeridian.</li>
 * </ol>
 */
final class TranscendentalProbes {

    private TranscendentalProbes() {
    }

    /**
     * Degrees to radians, as an explicit multiply rather than {@link Math#toRadians(double)}.
     *
     * <h4>Not a style preference - {@code Math.toRadians} is not bit-stable across JDKs</h4>
     *
     * <p>Measured here, and it invalidated the first version of this probe set. Java 8 computes
     * {@code angdeg / 180.0 * PI}; Java 9 changed it to a multiply by a precomputed
     * {@code DEGREES_TO_RADIANS} constant. The two differ by 1 ulp on <b>182 of the 721 whole
     * degrees in [-360, 360]</b>, which is 25% of them. So a probe list built with
     * {@code Math.toRadians} is a <em>different list</em> on Java 8 than on Java 9+, and the golden
     * table's results are then being compared against arguments that were never evaluated. That
     * presented as an apparent 64-ulp {@code StrictMath.sin} divergence on JDK 8 - which would have
     * been a serious finding had it been real. It was not: {@code StrictMath.sin} is bit-identical on
     * 8, 11, 21 and 26; only the argument had moved.
     *
     * <p>The constant below is {@code Math.PI / 180.0}, which is bit-identical to Java 9+'s
     * {@code DEGREES_TO_RADIANS} and to {@code ProjectionMath.DTR}. It is spelled out rather than
     * referenced so this class depends on nothing that another stream might edit.
     *
     * @param deg an angle in degrees
     * @return the angle in radians
     */
    static double deg2rad(double deg) {
        return deg * 0.017453292519943295;
    }

    /** Fixed so a failure is reproducible. Same constant the trig identity sweep uses. */
    static final long SEED = 0x50524f4a344aL; // "PROJ4J"

    /** The functions the golden covers, in the order the table is written. */
    static final String[] UNARY = {
            "sin", "cos", "tan",
            "asin", "acos", "atan",
            "exp", "log", "log10", "log1p", "expm1",
            "sinh", "cosh", "tanh",
            "cbrt", "sqrt",
    };

    /** Two-argument functions, evaluated over pairs from {@link #binaryProbes()}. */
    static final String[] BINARY = {"atan2", "pow", "hypot"};

    // ------------------------------------------------------------------
    // Unary probe sets, one per function, each restricted to that function's domain
    // ------------------------------------------------------------------

    /**
     * The probe list for a unary function.
     *
     * @param fn one of {@link #UNARY}
     * @return the arguments to evaluate, in a fixed order
     */
    static double[] unaryProbes(String fn) {
        List<Double> out = new ArrayList<Double>();
        if ("asin".equals(fn) || "acos".equals(fn)) {
            addBounded(out);
        } else if ("log".equals(fn) || "log10".equals(fn) || "sqrt".equals(fn)) {
            addPositive(out);
        } else if ("log1p".equals(fn)) {
            addAboveMinusOne(out);
        } else if (isPeriodic(fn)) {
            addPeriodic(out);
        } else {
            addUnbounded(out);
        }
        addSpecials(out, fn);
        return toArray(out);
    }

    /**
     * Whether a function reduces its argument modulo {@code pi/2}, and therefore needs the
     * {@code k*pi/4} lattice.
     *
     * <p>The distinction is worth making rather than sweeping everything with everything. The
     * lattice is ~5,000 probes and it is the <em>only</em> way to reach fdlibm's second and third
     * reduction rounds, its {@code n = +/-1} special case and its cancellation check - but those
     * branches exist solely in {@code sin}/{@code cos}/{@code tan}. Feeding the same 5,000 arguments
     * to {@code cbrt} would multiply the committed golden's size by about four while testing
     * nothing that a plain sweep does not already cover.
     *
     * @param fn the function name
     * @return true for the periodic family
     */
    private static boolean isPeriodic(String fn) {
        return "sin".equals(fn) || "cos".equals(fn) || "tan".equals(fn);
    }

    /**
     * Arguments in {@code [-1, 1]} - the domain of {@code asin}/{@code acos}, and the range that
     * every {@code sin}/{@code cos} result feeds into.
     *
     * <p>The edges matter more than the interior here: {@code aasin}/{@code aacos} exist in proj4j
     * precisely because ill-conditioned intermediates land a hair outside {@code [-1, 1]}, and the
     * error semantics of that case are a documented 1.5.0 behaviour change.
     */
    private static void addBounded(List<Double> out) {
        // Exact edges and their immediate neighbours on both sides.
        for (int s = -1; s <= 1; s += 2) {
            out.add((double) s);
            out.add(Math.nextDown((double) s) * 1.0);
            out.add(Math.nextUp(-1.0) * (s == -1 ? 1.0 : -1.0));
        }
        out.add(0.0);
        out.add(-0.0);
        // Deliberately NOT seeded with StrictMath.sin(deg2rad(deg)), although those are the values
        // proj4j really feeds to asin/acos. Generating a probe with the function under test makes
        // the probe list circular: if StrictMath.sin ever moved, the arguments AND the expected
        // results would both move and the failure would be unreadable. The uniform sweep and random
        // fill below cover [-1, 1] densely enough without that coupling.
        // Uniform interior sweep plus a fixed-seed random fill.
        for (int i = -256; i <= 256; i++) {
            out.add(i / 256.0);
        }
        Random r = new Random(SEED ^ 0x5A5AL);
        for (int i = 0; i < 1024; i++) {
            out.add(r.nextDouble() * 2.0 - 1.0);
        }
        // Subnormal and tiny, where the polynomial short circuits.
        out.add(Double.MIN_VALUE);
        out.add(-Double.MIN_VALUE);
        out.add(0x1.0p-27);
        out.add(0x1.0p-28);
        out.add(Math.nextDown(0x1.0p-27));
    }

    /** Strictly positive arguments, for {@code log}, {@code log10} and {@code sqrt}. */
    private static void addPositive(List<Double> out) {
        out.add(1.0);
        out.add(Math.nextUp(1.0));
        out.add(Math.nextDown(1.0));
        out.add(2.0);
        out.add(0.5);
        out.add(10.0);
        out.add(Math.E);
        out.add(Math.PI);
        out.add(Double.MIN_VALUE);
        out.add(Double.MIN_NORMAL);
        out.add(Double.MAX_VALUE);
        // Powers of two straddle log's exponent extraction.
        for (int k = -1074; k <= 1023; k += 37) {
            out.add(StrictMath.pow(2.0, k));
        }
        // The 1 +/- eps neighbourhood, where log switches from the table to the poly.
        for (int i = 1; i <= 64; i++) {
            out.add(1.0 + i * 0x1.0p-52);
            out.add(1.0 - i * 0x1.0p-53);
        }
        // Ellipsoid-scale quantities: 1-es, 1-e, (1-e)/(1+e) for what proj4j ships.
        for (int i = 0; i < ES.length; i++) {
            double es = ES[i];
            double e = StrictMath.sqrt(es);
            out.add(1.0 - es);
            out.add(1.0 - e);
            out.add((1.0 - e) / (1.0 + e));
            out.add(1.0 + e);
        }
        Random r = new Random(SEED ^ 0x0F0FL);
        for (int i = 0; i < 1024; i++) {
            // Log-uniform over the whole positive range: exercises every exponent.
            out.add(StrictMath.pow(2.0, r.nextDouble() * 2000.0 - 1000.0) * (1.0 + r.nextDouble()));
        }
    }

    /** Arguments greater than {@code -1}, for {@code log1p}. */
    private static void addAboveMinusOne(List<Double> out) {
        out.add(-1.0);
        out.add(Math.nextUp(-1.0));
        out.add(0.0);
        out.add(-0.0);
        out.add(Math.nextUp(0.0));
        out.add(Math.nextDown(0.0));
        // The small-argument regime is the reason log1p exists at all; sweep it densely.
        for (int k = -60; k <= 0; k++) {
            out.add(StrictMath.pow(2.0, k));
            out.add(-StrictMath.pow(2.0, k) * 0.5);
        }
        for (int i = -512; i <= 512; i++) {
            out.add(i * 0x1.0p-30);
        }
        out.add(Double.MAX_VALUE);
        Random r = new Random(SEED ^ 0x3C3CL);
        for (int i = 0; i < 1024; i++) {
            out.add(StrictMath.pow(2.0, r.nextDouble() * 60.0 - 40.0) * (r.nextBoolean() ? 1 : -1) * 0.5);
        }
    }

    /**
     * Arguments over the whole double range for functions that do <em>not</em> reduce modulo
     * {@code pi/2}: {@code atan}, {@code exp}, {@code expm1}, {@code sinh}, {@code cosh},
     * {@code tanh}, {@code cbrt}.
     */
    private static void addUnbounded(List<Double> out) {
        addCommonRealLine(out);
        Random r = new Random(SEED ^ 0x1234L);
        for (int i = 0; i < 1024; i++) {
            out.add(r.nextDouble() * 8.0 * Math.PI - 4.0 * Math.PI);
        }
        Random r2 = new Random(SEED ^ 0x9876L);
        for (int i = 0; i < 768; i++) {
            out.add(StrictMath.pow(2.0, r2.nextDouble() * 120.0 - 60.0) * (r2.nextBoolean() ? 1 : -1));
        }
    }

    /**
     * Arguments for {@code sin}, {@code cos} and {@code tan}: everything
     * {@link #addUnbounded(List)} covers, plus the {@code k*pi/4} lattice.
     *
     * <p>The lattice is the important part and it is the reason this list is separate. fdlibm's
     * {@code sin}/{@code cos}/{@code tan} reduce modulo {@code pi/2}, and every branch of that
     * reduction - the {@code |x| ~< pi/4} short circuit, the {@code n = +/-1} special case, the
     * cancellation check, and the second and third reduction rounds - is selected by how close the
     * argument sits to a multiple of {@code pi/4}. Random arguments hit exactly none of them, so a
     * sweep without the lattice would leave the branches that actually differ between
     * implementations completely untested while looking thorough.
     */
    private static void addPeriodic(List<Double> out) {
        addCommonRealLine(out);
        // The k*pi/4 and k*pi/2 lattice with two neighbours either side.
        for (int k = -256; k <= 256; k++) {
            addNeighbourhood(out, k * (Math.PI / 4.0));
            addNeighbourhood(out, k * (Math.PI / 2.0));
        }
        // fdlibm's own kernel thresholds and the multi-word reduction entry point.
        out.add(0x1.0p-27);
        out.add(0x1.0p-28);
        out.add(Math.nextDown(0x1.0p-27));
        out.add(Math.nextUp(0x1.0p-28));
        addNeighbourhood(out, 0x1.0p19 * (Math.PI / 2.0));
        // __kernel_rem_pio2's multi-word limb arithmetic, including its recomputation loop and the
        // textbook worst case for argument reduction.
        out.add(6381956970095103.0 * StrictMath.pow(2.0, 797));
        for (int k = 0; k <= 1000; k += 25) {
            out.add(Math.PI * StrictMath.pow(2.0, k));
        }
        Random r = new Random(SEED ^ 0x1234L);
        for (int i = 0; i < 1024; i++) {
            out.add(r.nextDouble() * 8.0 * Math.PI - 4.0 * Math.PI);
        }
        Random r2 = new Random(SEED ^ 0x9876L);
        for (int i = 0; i < 768; i++) {
            out.add(StrictMath.pow(2.0, r2.nextDouble() * 120.0 - 60.0) * (r2.nextBoolean() ? 1 : -1));
        }
    }

    /** The part of the real-line sweep every unbounded function shares. */
    private static void addCommonRealLine(List<Double> out) {
        out.add(0.0);
        out.add(-0.0);
        // Latitudes and longitudes in radians, on whole and part degrees: the real workload.
        for (int deg = -180; deg <= 180; deg++) {
            out.add(deg2rad(deg));
        }
        for (int i = 0; i < FRACTIONAL_DEGREES.length; i++) {
            out.add(deg2rad(FRACTIONAL_DEGREES[i]));
            out.add(deg2rad(-FRACTIONAL_DEGREES[i]));
        }
        out.add(1.0e10);
        out.add(1.0e100);
        out.add(Double.MAX_VALUE);
        out.add(-Double.MAX_VALUE);
        out.add(Double.MIN_VALUE);
        out.add(-Double.MIN_VALUE);
        out.add(Double.MIN_NORMAL);
        // exp/sinh/cosh overflow and underflow edges, to the last representable double.
        out.add(709.782712893384);
        out.add(710.0);
        out.add(-745.1332191019411);
        out.add(-746.0);
        out.add(-0x1.74385446d71c3p9);
    }

    private static void addNeighbourhood(List<Double> out, double x) {
        double up = x;
        double down = x;
        out.add(x);
        for (int i = 0; i < 2; i++) {
            up = Math.nextUp(up);
            down = Math.nextDown(down);
            out.add(up);
            out.add(down);
        }
    }

    /**
     * Special values.
     *
     * <p>Included for every function, in the domain-restricted lists too: a function asked for
     * {@code asin(2.0)} must return {@code NaN} identically everywhere, and that is exactly the
     * kind of edge where an implementation substitution shows up.
     */
    private static void addSpecials(List<Double> out, String fn) {
        out.add(Double.NaN);
        out.add(Double.POSITIVE_INFINITY);
        out.add(Double.NEGATIVE_INFINITY);
        out.add(0.0);
        out.add(-0.0);
        if ("asin".equals(fn) || "acos".equals(fn)) {
            out.add(2.0);
            out.add(-2.0);
            out.add(1.0 + 0x1.0p-52);
        }
        if ("log".equals(fn) || "log10".equals(fn) || "sqrt".equals(fn)) {
            out.add(-1.0);
            out.add(-0.5);
        }
        if ("log1p".equals(fn)) {
            out.add(-2.0);
            out.add(Math.nextDown(-1.0));
        }
    }

    // ------------------------------------------------------------------
    // Binary probes
    // ------------------------------------------------------------------

    /**
     * Pairs for {@code atan2}, {@code pow} and {@code hypot}, as a flat array of
     * {@code [x0, y0, x1, y1, ...]}.
     *
     * <p>{@code pow}'s special-value fast paths are here on purpose. An earlier measurement on this
     * project concluded {@code StrictMath.pow} allocates nothing, having only ever measured
     * {@code y = 0.5}, which returns before the array declarations; the real figure on a general
     * exponent is 96 B/op. The same trap applies to a bit-identity claim, so the exponent list
     * spans the fast paths <em>and</em> the general path.
     */
    static double[] binaryProbes() {
        List<Double> out = new ArrayList<Double>();
        double[] mags = {
                0.0, -0.0, 1.0, -1.0, 0.5, 2.0, 3.0, 10.0, Math.PI, Math.E,
                1.0e-300, 1.0e300, Double.MIN_VALUE, Double.MIN_NORMAL, Double.MAX_VALUE,
                Double.NaN, Double.POSITIVE_INFINITY, Double.NEGATIVE_INFINITY,
                0x1.0p-27, 0x1.0p19, 6378137.0, 6356752.314245179,
        };
        // Every ordered pair of the magnitude list: covers all sign and special-value combinations.
        for (int i = 0; i < mags.length; i++) {
            for (int j = 0; j < mags.length; j++) {
                out.add(mags[i]);
                out.add(mags[j]);
            }
        }
        // atan2 across all four quadrants on whole degrees - the real geodetic workload.
        for (int deg = -180; deg <= 180; deg++) {
            double a = deg2rad(deg);
            out.add(StrictMath.sin(a));
            out.add(StrictMath.cos(a));
        }
        // pow exponents that matter to proj4j: the tsfn/phi2 family uses e/2 and 1/n exponents,
        // and the special-value branches are y in {0, 0.5, 1, 2}.
        double[] powY = {0.0, 0.5, 1.0, 2.0, -1.0, -0.5, 0.37, 1.0 / 3.0, 0.0818191908426215 / 2.0};
        for (int i = 0; i < ES.length; i++) {
            double e = StrictMath.sqrt(ES[i]);
            for (int j = 0; j < powY.length; j++) {
                out.add((1.0 - e) / (1.0 + e));
                out.add(powY[j]);
            }
        }
        // hypot with operands spanning many exponents apart, where the scaled form differs most
        // from sqrt(x*x + y*y) - the substitution numerics.md prescribes for the hot path.
        for (int k = -400; k <= 400; k += 17) {
            out.add(1.0);
            out.add(StrictMath.pow(2.0, k));
        }
        Random r = new Random(SEED ^ 0xBEEFL);
        for (int i = 0; i < 1024; i++) {
            out.add(r.nextDouble() * 4.0 - 2.0);
            out.add(r.nextDouble() * 4.0 - 2.0);
        }
        Random r2 = new Random(SEED ^ 0xCAFEL);
        for (int i = 0; i < 512; i++) {
            out.add(StrictMath.pow(2.0, r2.nextDouble() * 200.0 - 100.0));
            out.add(r2.nextDouble() * 6.0 - 3.0);
        }
        return toArray(out);
    }

    // ------------------------------------------------------------------
    // Evaluation, shared so the generator and the test cannot disagree
    // ------------------------------------------------------------------

    /**
     * Evaluates {@code StrictMath.<fn>(x)}.
     *
     * @param fn one of {@link #UNARY}
     * @param x  the argument
     * @return the result
     */
    static double strictUnary(String fn, double x) {
        if ("sin".equals(fn)) return StrictMath.sin(x);
        if ("cos".equals(fn)) return StrictMath.cos(x);
        if ("tan".equals(fn)) return StrictMath.tan(x);
        if ("asin".equals(fn)) return StrictMath.asin(x);
        if ("acos".equals(fn)) return StrictMath.acos(x);
        if ("atan".equals(fn)) return StrictMath.atan(x);
        if ("exp".equals(fn)) return StrictMath.exp(x);
        if ("log".equals(fn)) return StrictMath.log(x);
        if ("log10".equals(fn)) return StrictMath.log10(x);
        if ("log1p".equals(fn)) return StrictMath.log1p(x);
        if ("expm1".equals(fn)) return StrictMath.expm1(x);
        if ("sinh".equals(fn)) return StrictMath.sinh(x);
        if ("cosh".equals(fn)) return StrictMath.cosh(x);
        if ("tanh".equals(fn)) return StrictMath.tanh(x);
        if ("cbrt".equals(fn)) return StrictMath.cbrt(x);
        if ("sqrt".equals(fn)) return StrictMath.sqrt(x);
        throw new IllegalArgumentException("unknown unary function: " + fn);
    }

    /**
     * Evaluates {@code Math.<fn>(x)} - the non-strict counterpart, used only as the negative
     * control.
     *
     * @param fn one of {@link #UNARY}
     * @param x  the argument
     * @return the result
     */
    static double mathUnary(String fn, double x) {
        if ("sin".equals(fn)) return Math.sin(x);
        if ("cos".equals(fn)) return Math.cos(x);
        if ("tan".equals(fn)) return Math.tan(x);
        if ("asin".equals(fn)) return Math.asin(x);
        if ("acos".equals(fn)) return Math.acos(x);
        if ("atan".equals(fn)) return Math.atan(x);
        if ("exp".equals(fn)) return Math.exp(x);
        if ("log".equals(fn)) return Math.log(x);
        if ("log10".equals(fn)) return Math.log10(x);
        if ("log1p".equals(fn)) return Math.log1p(x);
        if ("expm1".equals(fn)) return Math.expm1(x);
        if ("sinh".equals(fn)) return Math.sinh(x);
        if ("cosh".equals(fn)) return Math.cosh(x);
        if ("tanh".equals(fn)) return Math.tanh(x);
        if ("cbrt".equals(fn)) return Math.cbrt(x);
        if ("sqrt".equals(fn)) return Math.sqrt(x);
        throw new IllegalArgumentException("unknown unary function: " + fn);
    }

    /**
     * Evaluates {@code StrictMath.<fn>(x, y)}.
     *
     * @param fn one of {@link #BINARY}
     * @param x  the first argument
     * @param y  the second argument
     * @return the result
     */
    static double strictBinary(String fn, double x, double y) {
        if ("atan2".equals(fn)) return StrictMath.atan2(x, y);
        if ("pow".equals(fn)) return StrictMath.pow(x, y);
        if ("hypot".equals(fn)) return StrictMath.hypot(x, y);
        throw new IllegalArgumentException("unknown binary function: " + fn);
    }

    /**
     * Evaluates {@code Math.<fn>(x, y)} - the negative control.
     *
     * @param fn one of {@link #BINARY}
     * @param x  the first argument
     * @param y  the second argument
     * @return the result
     */
    static double mathBinary(String fn, double x, double y) {
        if ("atan2".equals(fn)) return Math.atan2(x, y);
        if ("pow".equals(fn)) return Math.pow(x, y);
        if ("hypot".equals(fn)) return Math.hypot(x, y);
        throw new IllegalArgumentException("unknown binary function: " + fn);
    }

    // ------------------------------------------------------------------

    /**
     * Squared eccentricities of the ellipsoids that carry the most traffic, so the probes include
     * the exact intermediates proj4j evaluates rather than only synthetic ones.
     *
     * <p>Values are computed from {@code a} and {@code rf} rather than copied, so a correction to
     * an ellipsoid definition cannot leave a stale constant here. They are only probe
     * <em>arguments</em>: nothing asserts they equal what {@code datum/Ellipsoid} holds, and this
     * class deliberately does not import it, so a concurrent edit there cannot red this test.
     */
    private static final double[] ES = buildEs();

    private static double[] buildEs() {
        // {inverse flattening} for WGS84/GRS80, Clarke 1866, Bessel 1841, Airy 1830, Krassovsky.
        double[] rf = {298.257223563, 298.257222101, 294.9786982, 299.1528128, 299.3249646, 298.3};
        double[] es = new double[rf.length + 1];
        for (int i = 0; i < rf.length; i++) {
            double f = 1.0 / rf[i];
            es[i] = f * (2.0 - f);
        }
        es[rf.length] = 0.0; // the sphere: es == 0 takes a different branch throughout proj4j
        return es;
    }

    /**
     * Fractional degrees taken from places where the corpus and the defect register put probes:
     * the {@code adams_ws2} antimeridian row, the tmerc seam, and the latitudes at which the
     * numerical core's helpers were measured worst.
     */
    private static final double[] FRACTIONAL_DEGREES = {
            179.999, 179.9999, 180.0, 0.5, 1.5, 3.0, 6.0, 20.0, 45.0,
            2.8, 18.0, 20.8, 42.0, 49.0, 70.0, 72.6, 75.0, 89.9, 89.999, 90.0,
            1.0e-12 * 180.0 / Math.PI, 122.4, 37.8,
    };

    /**
     * A 64-bit digest of a probe list's raw argument bits.
     *
     * <p>Committed alongside each golden section, and it is the guard that earns its keep: without
     * it, a probe list that generates <em>different arguments</em> on a different JDK produces a
     * flood of result mismatches whose message names an argument that looks perfectly reasonable.
     * That happened - see {@link #deg2rad(double)} - and cost real diagnosis time. With the digest,
     * the same situation fails once, immediately, saying the arguments moved.
     *
     * <p>FNV-1a over the eight bytes of each argument, most significant first. Any mixing function
     * would do; what matters is that it is defined here in Java arithmetic on {@code long}, which is
     * exact and reproducible on every JVM, rather than by a library whose implementation could vary.
     *
     * @param xs the argument list
     * @return the digest
     */
    static long digest(double[] xs) {
        long h = 0xcbf29ce484222325L;
        for (int i = 0; i < xs.length; i++) {
            long b = Double.doubleToRawLongBits(xs[i]);
            for (int shift = 56; shift >= 0; shift -= 8) {
                h ^= (b >>> shift) & 0xffL;
                h *= 0x100000001b3L;
            }
        }
        return h;
    }

    private static double[] toArray(List<Double> in) {
        double[] out = new double[in.size()];
        for (int i = 0; i < out.length; i++) {
            out[i] = in.get(i).doubleValue();
        }
        return out;
    }
}
