/*******************************************************************************
 * Copyright 2026
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *******************************************************************************/

package org.locationtech.proj4j.proj.adams;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertNotEquals;
import static org.junit.Assert.assertTrue;

import org.junit.Test;
import org.locationtech.proj4j.util.EllipticIntegral;

/**
 * Pins the constants and the series in {@link EllipticIntegral} against PROJ 9.8.1's
 * {@code src/projections/adams.cpp}.
 *
 * <p>These are not accuracy tests. Every one of them asserts <em>bit or near-bit fidelity to an
 * approximation upstream chose</em>, because the 3,443 expected values in the corpus for this
 * family were generated by that approximation. A change that makes any of these assertions fail
 * by "improving" the mathematics breaks roughly 3,400 conformance assertions.
 */
public class EllipticIntegralTest {

    /**
     * {@code adams.cpp:81} writes {@code RSQRT2} as a 28-digit decimal. The nearest
     * {@code double} to it is exactly {@code Math.sqrt(0.5)} and exactly one ulp away from
     * {@code 1.0 / Math.sqrt(2.0)}.
     *
     * <p>The negative half of this is the point: the two spellings of "one over root two" are
     * <em>different doubles</em>, and only one of them is upstream's.
     */
    @Test
    public void rsqrt2IsSqrtOfAHalfAndNotOneOverSqrtTwo() {
        assertEquals("RSQRT2 must be bit-equal to Math.sqrt(0.5)",
                Double.doubleToLongBits(Math.sqrt(0.5)),
                Double.doubleToLongBits(EllipticIntegral.RSQRT2));

        assertNotEquals("1.0/Math.sqrt(2.0) is one ulp away from adams.cpp's RSQRT2 and must not "
                        + "be substituted for it",
                Double.doubleToLongBits(1.0 / Math.sqrt(2.0)),
                Double.doubleToLongBits(EllipticIntegral.RSQRT2));

        // Exactly one ulp apart, and 1/sqrt(2) is the smaller of the two:
        //   adams.cpp's RSQRT2   0x1.6a09e667f3bcdp-1
        //   1.0/Math.sqrt(2.0)   0x1.6a09e667f3bccp-1
        assertEquals(Math.nextDown(EllipticIntegral.RSQRT2), 1.0 / Math.sqrt(2.0), 0.0);
        assertEquals(-1L, Double.doubleToLongBits(1.0 / Math.sqrt(2.0))
                - Double.doubleToLongBits(EllipticIntegral.RSQRT2));
    }

    /** {@code M_2_PI} inside {@code ell_int_5} is bit-equal to Java's {@code 2.0 / Math.PI}. */
    @Test
    public void twoOverPiIsBitEqualToTheCMacro() {
        assertEquals(Double.doubleToLongBits(0.63661977236758134308),
                Double.doubleToLongBits(2.0 / Math.PI));
    }

    /**
     * {@code ellInt5(pi/2)} is {@code 1.854074716833181} — <b>not</b> the true
     * {@code K(1/2) = 1.854074677301372}, and not {@link EllipticIntegral#K_HALF}. The two
     * constants coexist inside one upstream function on purpose.
     */
    @Test
    public void seriesAtPiOverTwoIsNotTheAccurateK() {
        double series = EllipticIntegral.ellInt5(Math.PI / 2);
        assertEquals(1.854074716833181, series, 1e-15);

        assertNotEquals("the series value and the accurate K(1/2) literal must stay distinct",
                Double.doubleToLongBits(series),
                Double.doubleToLongBits(EllipticIntegral.K_HALF));

        // 3.95e-08 apart: 0.25 m at +R=6370997, i.e. 250x the 1 mm gie tolerance.
        double delta = series - EllipticIntegral.K_HALF;
        assertEquals(3.9531809e-08, delta, 1e-14);
        assertTrue("the gap is 0.25 m at +R=6370997", delta * 6370997 > 0.25);
    }

    /** {@code K_HALF} is {@code adams.cpp:209}'s literal, and {@code shd} is twice it. */
    @Test
    public void peirceShiftIsTwiceTheAccurateK() {
        assertEquals(1.8540746773013719, EllipticIntegral.K_HALF, 0.0);
        assertEquals(3.7081493546027438, EllipticIntegral.PEIRCE_SHIFT, 0.0);
    }

    /**
     * {@code guyou}'s pole constant is the truncated literal {@code 1.85407}, five decimals, and
     * is 30 m from the series value at {@code +R=6370997}. {@code guyou.gie:2122-2131} asserts it
     * at {@code +R=1} with a 1 mm tolerance.
     */
    @Test
    public void guyouPoleIsTheTruncatedLiteral() {
        assertEquals(1.85407, EllipticIntegral.GUYOU_POLE, 0.0);
        double gap = EllipticIntegral.ellInt5(Math.PI / 2) - EllipticIntegral.GUYOU_POLE;
        assertEquals(30.05, gap * 6370997, 0.05);
    }

    /**
     * The series is odd in {@code phi} <em>exactly</em>: the Chebyshev argument depends on
     * {@code phi^2} and the result is scaled by {@code phi}. Callers pass signed amplitudes and
     * rely on it.
     */
    @Test
    public void seriesIsExactlyOdd() {
        for (double phi = 0; phi <= Math.PI / 2; phi += 0.01) {
            assertEquals(-EllipticIntegral.ellInt5(phi), EllipticIntegral.ellInt5(-phi), 0.0);
        }
        assertEquals(0.0, EllipticIntegral.ellInt5(0.0), 0.0);
    }

    /**
     * Values recomputed independently at 60 decimal digits from the Clenshaw recurrence with
     * upstream's coefficients, so a coefficient transcription slip or a reversed loop shows up
     * here rather than 3,400 assertions later.
     */
    @Test
    public void seriesMatchesAnIndependentEvaluationOfTheSameRecurrence() {
        assertEquals(0.100083357563412578, EllipticIntegral.ellInt5(0.1), 1e-14);
        assertEquals(0.510467156346209038, EllipticIntegral.ellInt5(0.5), 1e-14);
        assertEquals(1.083216798343482417, EllipticIntegral.ellInt5(1.0), 1e-14);
        assertEquals(1.613684817095107004, EllipticIntegral.ellInt5(1.4), 1e-14);
        assertEquals(1.854074716833181079, EllipticIntegral.ellInt5(Math.PI / 2), 1e-14);
    }

    /**
     * The series is <em>worse</em> than a true elliptic integral by 420x the corpus tolerance,
     * and that is the whole point. Measured at upstream's own worst case, {@code phi = 1.27699}.
     *
     * <p>{@code F(1.27699 | 1/2)} was computed to 60 digits by Carlson {@code RF} duplication
     * outside this repository; the value is inlined because building a Carlson implementation in
     * {@code core} is exactly what the port must not do.
     */
    @Test
    public void seriesIsFarFromTheTrueIntegralAtItsWorstPoint() {
        double phi = 1.27699;
        double trueValue = 1.4442330049580361;
        double error = Math.abs(EllipticIntegral.ellInt5(phi) - trueValue);
        assertEquals(6.614043e-08, error, 1e-13);
        assertTrue("0.42 m at +R=6370997 - 420x the 1 mm gie tolerance",
                error * 6370997 > 0.42);
        assertFalse("if this ever becomes accurate, ~3,400 gie assertions break",
                error * 6370997 < 0.001);
    }
}
