/*
 * Copyright 2026 the Proj4J contributors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 */
package org.locationtech.proj4j.golden;

import org.locationtech.proj4j.CRSFactory;
import org.locationtech.proj4j.CoordinateReferenceSystem;
import org.locationtech.proj4j.CoordinateTransform;
import org.locationtech.proj4j.CoordinateTransformFactory;
import org.locationtech.proj4j.ProjCoordinate;

import java.io.File;
import java.io.IOException;
import java.io.Writer;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * Writes a golden table: for every input case, the forward transform's output, the inverse applied to
 * that output, and the advisory {@code Projection.inside} flag.
 *
 * <h2>The 1.4.3 API constraint</h2>
 *
 * <b>This class must compile and run unchanged against released proj4j 1.4.3 and against the working
 * tree.</b> That is the entire reason the module exists: a baseline generated by different code than
 * the comparison run is not a baseline. So it touches only API that shipped in 1.4.3 —
 * {@link CRSFactory}, {@link CoordinateReferenceSystem}, {@link CoordinateTransform},
 * {@link CoordinateTransformFactory}, {@link ProjCoordinate},
 * {@code org.locationtech.proj4j.Proj4jException}, and {@code proj.Projection.inside(double,double)}
 * (present and unchanged in 1.4.3; the {@code inside} column is required by the plan and there is no
 * other way to read it). No reflection, no {@code Registry} enumeration, nothing added this week. If
 * a change to {@code core} breaks the default-profile compile of this file, that is a signal.
 *
 * <h2>What is deliberately NOT done</h2>
 *
 * <ul>
 * <li><b>No destination poisoning.</b> The stale-{@code dst} family of defects (six projections whose
 *     {@code projectInverse} reads the unmutated parameter instead of the output struct) would be
 *     caught by pre-filling the destination with {@code 1e300}, and the defect notes recommend exactly
 *     that. It cannot work from this API: {@code BasicCoordinateTransform.transform} opens with
 *     {@code tgt.setValue(src)}, so the caller's destination contents are unobservable. That probe
 *     belongs in a unit test in {@code core}, not here.</li>
 * <li><b>No tolerance, no expected value, no pass/fail.</b> A golden row is an observation. This
 *     suite has no opinion about whether {@code 89.9568} degrees of latitude error is correct — see
 *     README.md, "Policy": gie always wins over a golden rule.</li>
 * </ul>
 *
 * <h2>Determinism</h2>
 *
 * The output depends on the order of generation, because
 * {@code parser/Proj4Parser.java:53} mutates process-global static {@code Datum} singletons
 * ({@code Datum.NAD27.setGrids(null)} and friends) as a side effect of parsing. The order is therefore
 * fixed and total — {@code (section, key)} in US-ASCII order — and both sides of a comparison walk it
 * identically. Parsed CRS are cached per run, which changes how many times each idempotent global
 * write happens but not the order in which distinct writes first occur.
 */
public final class GoldenGenerator {

    /** Exit code when generation completed. */
    public static final int OK = 0;

    private final CRSFactory crsFactory = new CRSFactory();
    private final CoordinateTransformFactory ctFactory = new CoordinateTransformFactory();

    /**
     * Cache of parsed CRS, keyed by name-or-proj-string. Purely a speed measure:
     * {@code io/Proj4FileReader.readParametersFromFile} re-opens and re-{@code StreamTokenizer}-scans
     * the 888 KB {@code epsg} resource on <em>every</em> call, and the CSV section asks for the same
     * few hundred codes ~5,000 times.
     */
    private final Map<String, Object> crsCache = new HashMap<String, Object>();

    private final Counters counters = new Counters();

    /** Tallies written to {@code golden-summary.txt} and printed at the end of a run. */
    public static final class Counters {
        public int cases;
        public int rows;
        public int ok;
        public int exceptions;
        public int noProbe;
        public int nonFinite;
    }

    public Counters counters() {
        return counters;
    }

    // ------------------------------------------------------------------------------- main

    /**
     * Usage: {@code GoldenGenerator <outputDir> [goldenDir] [csvDir]}.
     *
     * <p>{@code goldenDir} holds the committed inputs ({@code probes.tsv}, {@code pairs.tsv}) and
     * defaults to the {@code golden.dir} system property. {@code csvDir} holds the MetaCRS CSVs and
     * defaults to {@code <goldenDir>/../core/src/test/resources}.
     */
    public static void main(String[] args) throws IOException {
        if (args.length < 1) {
            System.err.println("usage: GoldenGenerator <outputDir> [goldenDir] [csvDir]");
            System.exit(2);
        }
        File out = new File(args[0]);
        File goldenDir = args.length > 1 ? new File(args[1])
                : new File(System.getProperty("golden.dir", "."));
        File csvDir = args.length > 2 ? new File(args[2])
                : defaultCsvDir(goldenDir);

        Counters c = new GoldenGenerator().generate(out, goldenDir, csvDir);
        System.out.println("golden: " + c.cases + " cases, " + c.rows + " rows, "
                + c.ok + " OK, " + c.exceptions + " EXC, " + c.noProbe + " NO_PROBE, "
                + c.nonFinite + " rows with a non-finite ordinate");
        System.exit(OK);
    }

    public static File defaultCsvDir(File goldenDir) {
        return new File(goldenDir.getParentFile() == null ? new File("..") : goldenDir.getParentFile(),
                "core/src/test/resources");
    }

    // --------------------------------------------------------------------------- generation

    public Counters generate(File outDir, File goldenDir, File csvDir) throws IOException {
        List<RegistryDict.Def> defs = RegistryDict.readAll();
        Map<String, RegistryDict.Def> byKey = InputSet.index(defs);

        List<InputSet.Case> cases = new ArrayList<InputSet.Case>(60000);
        cases.addAll(InputSet.csv(MetaCrsCsv.readAll(csvDir), byKey));
        cases.addAll(InputSet.pairs(new File(goldenDir, "pairs.tsv"), byKey));
        cases.addAll(InputSet.registry(defs));
        cases.addAll(InputSet.synthetic());
        Collections.sort(cases, new Comparator<InputSet.Case>() {
            public int compare(InputSet.Case a, InputSet.Case b) {
                int r = a.section.compareTo(b.section);
                if (r != 0) return r;
                return a.key.compareTo(b.key);
            }
        });

        Probes.Table probes = Probes.read(new File(goldenDir, "probes.tsv"));

        Writer golden = GoldenFormat.writer(new File(outDir, GoldenFormat.GOLDEN_FILE));
        Writer index = GoldenFormat.writer(new File(outDir, GoldenFormat.INDEX_FILE));
        Writer messages = GoldenFormat.writer(new File(outDir, GoldenFormat.MESSAGES_FILE));
        try {
            golden.write(GoldenFormat.HEADER_GOLDEN);
            golden.write('\n');
            index.write(GoldenFormat.HEADER_INDEX);
            index.write('\n');
            messages.write(GoldenFormat.HEADER_MESSAGES);
            messages.write('\n');

            String prevSection = null;
            String prevKey = null;
            for (int i = 0; i < cases.size(); i++) {
                InputSet.Case c = cases.get(i);
                if (prevSection != null) {
                    int cmp = prevSection.compareTo(c.section);
                    if (cmp == 0) cmp = prevKey.compareTo(c.key);
                    if (cmp > 0) {
                        throw new IllegalStateException("cases out of order: "
                                + prevSection + "/" + prevKey + " then " + c.section + "/" + c.key);
                    }
                    if (cmp == 0) {
                        throw new IllegalStateException("duplicate case key: " + c.section + "/" + c.key);
                    }
                }
                prevSection = c.section;
                prevKey = c.key;

                counters.cases++;
                GoldenFormat.writeRow(index, c.section, c.key,
                        c.srcProj, c.tgtProj, c.paramKeys, c.datums);
                emit(golden, messages, c, probes);
            }
        } finally {
            golden.close();
            index.close();
            messages.close();
        }

        Writer summary = GoldenFormat.writer(new File(outDir, "golden-summary.txt"));
        try {
            summary.write("cases=" + counters.cases + "\n");
            summary.write("rows=" + counters.rows + "\n");
            summary.write("ok=" + counters.ok + "\n");
            summary.write("exceptions=" + counters.exceptions + "\n");
            summary.write("no_probe=" + counters.noProbe + "\n");
            summary.write("non_finite_rows=" + counters.nonFinite + "\n");
        } finally {
            summary.close();
        }
        return counters;
    }

    private void emit(Writer golden, Writer messages, InputSet.Case c, Probes.Table probes)
            throws IOException {
        double[][] coords = c.coords;
        int n;
        if (coords == null) {
            double[][] p = probes.get(c.section, c.key);
            if (p == null) {
                // A key present in the input set but absent from the committed probe table. Not an
                // error: it is how a def added to the dictionaries after the last probe regeneration
                // announces itself, instead of silently acquiring a made-up probe.
                for (int i = 0; i < Probes.PROBE_COUNT; i++) {
                    writeRow(golden, c, i, GoldenFormat.NO_PROBE,
                            Double.NaN, Double.NaN, Double.NaN,
                            Double.NaN, Double.NaN, Double.NaN, "-");
                    counters.noProbe++;
                }
                return;
            }
            n = Probes.PROBE_COUNT;
            coords = new double[n][3];
            for (int i = 0; i < n; i++) {
                coords[i][0] = p[i][0];
                coords[i][1] = p[i][1];
                coords[i][2] = 0.0;
            }
        } else {
            n = coords.length;
        }

        Object src = crs(c.srcName, c.srcParams);
        Object tgt = crs(c.tgtName, c.tgtParams);
        if (src instanceof Failure || tgt instanceof Failure) {
            Failure f = (Failure) (src instanceof Failure ? src : tgt);
            String stage = src instanceof Failure ? "crs-src" : "crs-tgt";
            for (int i = 0; i < n; i++) {
                writeRow(golden, c, i, GoldenFormat.EXC + f.type,
                        Double.NaN, Double.NaN, Double.NaN, Double.NaN, Double.NaN, Double.NaN, "-");
                message(messages, c, i, stage, f.message);
                counters.exceptions++;
            }
            return;
        }
        CoordinateReferenceSystem srcCrs = (CoordinateReferenceSystem) src;
        CoordinateReferenceSystem tgtCrs = (CoordinateReferenceSystem) tgt;

        Object fwd = transform(srcCrs, tgtCrs);
        Object inv = transform(tgtCrs, srcCrs);
        if (fwd instanceof Failure) {
            Failure f = (Failure) fwd;
            for (int i = 0; i < n; i++) {
                writeRow(golden, c, i, GoldenFormat.EXC + f.type,
                        Double.NaN, Double.NaN, Double.NaN, Double.NaN, Double.NaN, Double.NaN, "-");
                message(messages, c, i, "transform-fwd", f.message);
                counters.exceptions++;
            }
            return;
        }
        CoordinateTransform fwdT = (CoordinateTransform) fwd;
        CoordinateTransform invT = inv instanceof Failure ? null : (CoordinateTransform) inv;

        ProjCoordinate in = new ProjCoordinate();
        ProjCoordinate f1 = new ProjCoordinate();
        ProjCoordinate f2 = new ProjCoordinate();

        for (int i = 0; i < n; i++) {
            in.x = coords[i][0];
            in.y = coords[i][1];
            in.z = coords[i].length > 2 ? coords[i][2] : 0.0;

            String status = GoldenFormat.OK;
            String stage = null;
            String msg = null;
            String type = null;

            f1.x = Double.NaN;
            f1.y = Double.NaN;
            f1.z = Double.NaN;
            f2.x = Double.NaN;
            f2.y = Double.NaN;
            f2.z = Double.NaN;

            try {
                fwdT.transform(in, f1);
            } catch (Throwable t) {
                rethrowFatal(t);
                type = t.getClass().getName();
                stage = "fwd";
                msg = t.getMessage();
                f1.x = Double.NaN;
                f1.y = Double.NaN;
                f1.z = Double.NaN;
            }

            if (type == null) {
                if (invT == null) {
                    Failure f = (Failure) inv;
                    type = f.type;
                    stage = "transform-inv";
                    msg = f.message;
                } else {
                    try {
                        invT.transform(f1, f2);
                    } catch (Throwable t) {
                        rethrowFatal(t);
                        type = t.getClass().getName();
                        stage = "inv";
                        msg = t.getMessage();
                        f2.x = Double.NaN;
                        f2.y = Double.NaN;
                        f2.z = Double.NaN;
                    }
                }
            }

            if (type != null) {
                status = GoldenFormat.EXC + type;
                counters.exceptions++;
                message(messages, c, i, stage, msg);
            } else {
                counters.ok++;
            }

            String inside = "-";
            if (c.geographicInput) {
                inside = inside(tgtCrs, in.x, in.y);
            }
            writeRow(golden, c, i, status, f1.x, f1.y, f1.z, f2.x, f2.y, f2.z, inside);
            if (!isFinite(f1.x) || !isFinite(f1.y) || !isFinite(f1.z)
                    || !isFinite(f2.x) || !isFinite(f2.y) || !isFinite(f2.z)) {
                counters.nonFinite++;
            }
        }
    }

    /** {@code Double.isFinite} is Java 8; spelled out so the source level can drop if it must. */
    private static boolean isFinite(double d) {
        return !Double.isNaN(d) && !Double.isInfinite(d);
    }

    /**
     * The advisory domain flag. {@code Projection.inside} has <b>zero callers in {@code core}</b> —
     * it is dead code — so recording it here is the only place its value is observed. It is
     * <em>advisory</em>: proj4j does not consult it before transforming, so a {@code F} row is not a
     * failure and an {@code OK}/{@code F} combination is the normal case for anything probed near the
     * edge of its box.
     *
     * <p>It can throw: it routes through {@code ProjectionMath.normalizeLongitude}, which raises
     * {@code InvalidValueException} on a NaN or infinite argument. Hence three values, not two.
     */
    private static String inside(CoordinateReferenceSystem crs, double lon, double lat) {
        try {
            org.locationtech.proj4j.proj.Projection p = crs.getProjection();
            if (p == null) return "-";
            return p.inside(lon, lat) ? "T" : "F";
        } catch (Throwable t) {
            rethrowFatal(t);
            return "E";
        }
    }

    private void writeRow(Writer w, InputSet.Case c, int probe, String status,
                          double fx, double fy, double fz,
                          double ix, double iy, double iz, String inside) throws IOException {
        GoldenFormat.writeRow(w, c.section, c.key, Integer.toString(probe), status,
                GoldenFormat.hex(fx), GoldenFormat.hex(fy), GoldenFormat.hex(fz),
                GoldenFormat.hex(ix), GoldenFormat.hex(iy), GoldenFormat.hex(iz), inside);
        counters.rows++;
    }

    private void message(Writer w, InputSet.Case c, int probe, String stage, String msg)
            throws IOException {
        String text = stage + ": " + (msg == null ? "" : msg);
        GoldenFormat.writeRow(w, c.section, c.key, Integer.toString(probe),
                GoldenFormat.sanitise(text));
    }

    // ------------------------------------------------------------------ CRS and transforms

    private static final class Failure {
        final String type;
        final String message;

        Failure(Throwable t) {
            this.type = t.getClass().getName();
            this.message = t.getMessage();
        }
    }

    /** Returns a {@link CoordinateReferenceSystem} or a {@link Failure}; never throws. */
    private Object crs(String name, String[] params) {
        String cacheKey = params == null ? "N " + name : "P " + join(params);
        Object hit = crsCache.get(cacheKey);
        if (hit != null) return hit;
        Object result;
        try {
            CoordinateReferenceSystem c = params == null
                    ? crsFactory.createFromName(name)
                    : crsFactory.createFromParameters(name, params);
            // createFromParameters returns null for a null parameter array; createFromName throws
            // UnknownAuthorityCodeException. Neither should produce a null here, but a null CRS
            // would NPE deep inside CoordinateTransformFactory and lose the key, so it is recorded
            // as its own failure shape.
            result = c == null ? new Failure(new NullPointerException("null CRS for " + name)) : c;
        } catch (Throwable t) {
            rethrowFatal(t);
            result = new Failure(t);
        }
        crsCache.put(cacheKey, result);
        return result;
    }

    /** Returns a {@link CoordinateTransform} or a {@link Failure}; never throws. */
    private Object transform(CoordinateReferenceSystem src, CoordinateReferenceSystem tgt) {
        try {
            return ctFactory.createTransform(src, tgt);
        } catch (Throwable t) {
            rethrowFatal(t);
            return new Failure(t);
        }
    }

    /**
     * Catching {@link Throwable} is normally wrong, and here it is necessary: proj4j throws
     * {@code NoSuchElementException} from {@code Projection.setSouthernHemisphere} and
     * {@code setHeightOfOrbit}, {@code IllegalStateException} from {@code GeocentricConverter}, and a
     * bare {@code new Error()} from {@code datum/AxisOrder.fromString} — none of which are
     * {@code Proj4jException}. Recording them as rows is the point. A genuine VM error is rethrown so
     * an OOM does not masquerade as 45,000 identical {@code EXC:} rows.
     */
    private static void rethrowFatal(Throwable t) {
        if (t instanceof VirtualMachineError) throw (VirtualMachineError) t;
        if (t instanceof ThreadDeath) throw (ThreadDeath) t;
    }

    private static String join(String[] params) {
        StringBuilder sb = new StringBuilder();
        for (int i = 0; i < params.length; i++) {
            if (i > 0) sb.append(' ');
            sb.append(params[i]);
        }
        return sb.toString();
    }
}
