/*******************************************************************************
 * Copyright 2026
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *******************************************************************************/

package org.locationtech.proj4j.util;

/**
 * Auxiliary-latitude series coefficients, a port of PROJ 9.8.1's
 * {@code src/latitudes.cpp:238-420} ({@code pj_auxlat_coeffs}, {@code pj_polyval},
 * {@code pj_rectifying_radius}).
 *
 * <p>The framework is Karney's, <i>On auxiliary latitudes</i>, Survey Review 56,
 * 165-180 (2024). Conversions between any pair of auxiliary latitudes are Fourier
 * series in the source latitude whose coefficients are Taylor series in the third
 * flattening {@code n}, truncated at order 6. That suffices for full double
 * precision for {@code |f| <= 1/150} and is satisfactory for {@code |f| <= 1/50}.
 *
 * <p>The coefficient table is machine generated by the Maxima script
 * {@code auxlat.mac} bundled with GeographicLib, and is transcribed here verbatim
 * from upstream as <em>exact rational expressions</em> rather than decimal literals,
 * so that each entry is the correctly-rounded {@code double} nearest the exact
 * rational on every platform.
 *
 * <p>Only the upper triangular portion of each matrix is stored, and for the
 * conversions among {@code phi, beta, theta, mu} half the coefficients vanish (those
 * Taylor series are expansions in {@code n^2}), so the zero entries are excluded too.
 * All eight supported matrices are concatenated into one flat 150-element array,
 * indexed through {@link #PTRS}.
 *
 * <p><b>Only 8 of the 36 conversions are populated</b>, namely
 * {@code phi <-> mu} (meridian distance), {@code phi <-> chi} (transverse Mercator),
 * {@code phi <-> xi} (authalic latitude) and {@code chi <-> mu} (transverse Mercator).
 * Any other pair throws {@link IllegalArgumentException}.
 *
 * <p><b>Math vs StrictMath:</b> this class performs only {@code + - * /} and
 * {@link Math#sqrt}, all of which IEEE-754 specifies as exactly rounded, so every
 * coefficient produced here is bit-reproducible across architectures without needing
 * {@code StrictMath}. That is the whole point of deriving {@code n} from
 * {@code es} with one {@code sqrt} (see {@link #thirdFlattening}) instead of
 * upstream's {@code pow(tan(asin(e)/2), 2)}, which routes through three
 * platform-dependent libm calls.
 *
 * @see Clenshaw6
 */
public final strictfp class AuxLat {

    /** Geographic latitude, phi. */
    public static final int GEOGRAPHIC = 0;
    /** Parametric (reduced) latitude, beta. */
    public static final int PARAMETRIC = 1;
    /** Geocentric latitude, theta. */
    public static final int GEOCENTRIC = 2;
    /** Rectifying latitude, mu. */
    public static final int RECTIFYING = 3;
    /** Conformal latitude, chi. */
    public static final int CONFORMAL = 4;
    /** Authalic latitude, xi. */
    public static final int AUTHALIC = 5;

    /** The number of auxiliary latitudes. */
    public static final int NUMBER = 6;

    /**
     * The order of the expansion in {@code n}. Accidentally equal to
     * {@link #NUMBER}; upstream notes the coincidence explicitly.
     */
    public static final int ORDER = 6;

    /**
     * The flat Maxima-generated coefficient table, 150 doubles.
     *
     * <p>Generated by Maxima on 2025-03-23 19:13:00-04:00, transcribed from
     * {@code 9.8.1:src/latitudes.cpp:241-336}. Blocks in table order:
     * {@code C[phi,mu] C[phi,chi] C[phi,xi] C[mu,phi] C[mu,chi] C[chi,phi]
     * C[chi,mu] C[xi,phi]}, where {@code C[eta,zeta]} converts {@code zeta}
     * (the input) to {@code eta} (the output).
     */
    private static final double[] COEFFS = {
        // C[phi,mu]; even coeffs only
        3.0 / 2.0, -27.0 / 32.0, 269.0 / 512.0, 21.0 / 16.0, -55.0 / 32.0,
        6759.0 / 4096.0, 151.0 / 96.0, -417.0 / 128.0, 1097.0 / 512.0,
        -15543.0 / 2560.0, 8011.0 / 2560.0, 293393.0 / 61440.0,
        // C[phi,chi]
        2.0, -2.0 / 3.0, -2.0, 116.0 / 45.0, 26.0 / 45.0, -2854.0 / 675.0,
        7.0 / 3.0, -8.0 / 5.0, -227.0 / 45.0, 2704.0 / 315.0, 2323.0 / 945.0,
        56.0 / 15.0, -136.0 / 35.0, -1262.0 / 105.0, 73814.0 / 2835.0,
        4279.0 / 630.0, -332.0 / 35.0, -399572.0 / 14175.0, 4174.0 / 315.0,
        -144838.0 / 6237.0, 601676.0 / 22275.0,
        // C[phi,xi]
        4.0 / 3.0, 4.0 / 45.0, -16.0 / 35.0, -2582.0 / 14175.0,
        60136.0 / 467775.0, 28112932.0 / 212837625.0, 46.0 / 45.0,
        152.0 / 945.0, -11966.0 / 14175.0, -21016.0 / 51975.0,
        251310128.0 / 638512875.0, 3044.0 / 2835.0, 3802.0 / 14175.0,
        -94388.0 / 66825.0, -8797648.0 / 10945935.0, 6059.0 / 4725.0,
        41072.0 / 93555.0, -1472637812.0 / 638512875.0, 768272.0 / 467775.0,
        455935736.0 / 638512875.0, 4210684958.0 / 1915538625.0,
        // C[mu,phi]; even coeffs only
        -3.0 / 2.0, 9.0 / 16.0, -3.0 / 32.0, 15.0 / 16.0, -15.0 / 32.0,
        135.0 / 2048.0, -35.0 / 48.0, 105.0 / 256.0, 315.0 / 512.0,
        -189.0 / 512.0, -693.0 / 1280.0, 1001.0 / 2048.0,
        // C[mu,chi]
        1.0 / 2.0, -2.0 / 3.0, 5.0 / 16.0, 41.0 / 180.0, -127.0 / 288.0,
        7891.0 / 37800.0, 13.0 / 48.0, -3.0 / 5.0, 557.0 / 1440.0,
        281.0 / 630.0, -1983433.0 / 1935360.0, 61.0 / 240.0, -103.0 / 140.0,
        15061.0 / 26880.0, 167603.0 / 181440.0, 49561.0 / 161280.0,
        -179.0 / 168.0, 6601661.0 / 7257600.0, 34729.0 / 80640.0,
        -3418889.0 / 1995840.0, 212378941.0 / 319334400.0,
        // C[chi,phi]
        -2.0, 2.0 / 3.0, 4.0 / 3.0, -82.0 / 45.0, 32.0 / 45.0, 4642.0 / 4725.0,
        5.0 / 3.0, -16.0 / 15.0, -13.0 / 9.0, 904.0 / 315.0, -1522.0 / 945.0,
        -26.0 / 15.0, 34.0 / 21.0, 8.0 / 5.0, -12686.0 / 2835.0, 1237.0 / 630.0,
        -12.0 / 5.0, -24832.0 / 14175.0, -734.0 / 315.0, 109598.0 / 31185.0,
        444337.0 / 155925.0,
        // C[chi,mu]
        -1.0 / 2.0, 2.0 / 3.0, -37.0 / 96.0, 1.0 / 360.0, 81.0 / 512.0,
        -96199.0 / 604800.0, -1.0 / 48.0, -1.0 / 15.0, 437.0 / 1440.0,
        -46.0 / 105.0, 1118711.0 / 3870720.0, -17.0 / 480.0, 37.0 / 840.0,
        209.0 / 4480.0, -5569.0 / 90720.0, -4397.0 / 161280.0, 11.0 / 504.0,
        830251.0 / 7257600.0, -4583.0 / 161280.0, 108847.0 / 3991680.0,
        -20648693.0 / 638668800.0,
        // C[xi,phi]
        -4.0 / 3.0, -4.0 / 45.0, 88.0 / 315.0, 538.0 / 4725.0,
        20824.0 / 467775.0, -44732.0 / 2837835.0, 34.0 / 45.0, 8.0 / 105.0,
        -2482.0 / 14175.0, -37192.0 / 467775.0, -12467764.0 / 212837625.0,
        -1532.0 / 2835.0, -898.0 / 14175.0, 54968.0 / 467775.0,
        100320856.0 / 1915538625.0, 6007.0 / 14175.0, 24496.0 / 467775.0,
        -5884124.0 / 70945875.0, -23356.0 / 66825.0, -839792.0 / 19348875.0,
        570284222.0 / 1915538625.0,
    };

    /**
     * Start offset in {@link #COEFFS} of the matrix for conversion index
     * {@code k = NUMBER * auxout + auxin}. Length {@code NUMBER * NUMBER + 1 = 37};
     * a conversion is unsupported exactly when {@code PTRS[k] == PTRS[k + 1]}.
     */
    private static final int[] PTRS = {
        0,   0,   0,   0,   12,  33,  54,  54,  54,  54,  54,  54, 54,
        54,  54,  54,  54,  54,  54,  66,  66,  66,  66,  87,  87, 108,
        108, 108, 129, 129, 129, 150, 150, 150, 150, 150, 150,
    };

    /**
     * Coefficients of the rectifying-radius series, {@code ((2k-3)!! / (2k)!!)^2}
     * for {@code k = 0..3}.
     */
    private static final double[] COEFF_RAD = {1.0, 1.0 / 4.0, 1.0 / 64.0, 1.0 / 256.0};

    private AuxLat() {
    }

    /**
     * Computes the {@value #ORDER} Fourier coefficients for converting the auxiliary
     * latitude {@code auxin} (called zeta upstream) to {@code auxout} (eta).
     *
     * <p>Port of {@code pj_auxlat_coeffs}. {@code F[l] = C[eta,zeta] . P(n)} where
     * {@code P(n) = [n, n^2, n^3, ...]^T}.
     *
     * <p><b>The n-squared split is load bearing.</b> When both latitudes are
     * {@code <= RECTIFYING} (i.e. the {@code phi <-> mu} pair, the only such pair with
     * a populated table) the coefficient of each Fourier term is a polynomial in
     * {@code n^2} with 12 stored constants; for every other supported pair it is a
     * polynomial in {@code n} with 21. That branch is at
     * {@code 9.8.1:src/latitudes.cpp:342}.
     *
     * @param n      the third flattening, {@code (a - b) / (a + b)}
     * @param auxin  the input auxiliary latitude, one of the constants on this class
     * @param auxout the output auxiliary latitude
     * @param f      destination, at least {@value #ORDER} long; the first
     *               {@value #ORDER} elements are written
     * @throws IllegalArgumentException if either latitude is out of range, or the
     *                                  conversion between them is not one of the
     *                                  eight tabulated
     */
    public static void coeffs(double n, int auxin, int auxout, double[] f) {
        if (!(auxin >= 0 && auxin < NUMBER && auxout >= 0 && auxout < NUMBER)) {
            throw new IllegalArgumentException(
                    "Bad specification for auxiliary latitude: auxin=" + auxin
                            + " auxout=" + auxout);
        }
        final int k = NUMBER * auxout + auxin;
        int o = PTRS[k];
        if (o == PTRS[k + 1]) {
            throw new IllegalArgumentException(
                    "Unsupported conversion between auxiliary latitudes: "
                            + name(auxin) + " -> " + name(auxout));
        }
        double d = n;
        if (auxin <= RECTIFYING && auxout <= RECTIFYING) {
            final double n2 = n * n;
            for (int l = 0; l < ORDER; ++l) {
                final int m = (ORDER - l - 1) / 2; // order of polynomial in n^2
                f[l] = d * polyval(n2, COEFFS, o, m);
                o += m + 1;
                d *= n;
            }
        } else {
            for (int l = 0; l < ORDER; ++l) {
                final int m = ORDER - l - 1; // order of polynomial in n
                f[l] = d * polyval(n, COEFFS, o, m);
                o += m + 1;
                d *= n;
            }
        }
        // Invariant from upstream's commented-out assert: o == PTRS[k + 1].
    }

    /**
     * Convenience form of {@link #coeffs(double, int, int, double[])} returning a
     * freshly allocated array of length {@value #ORDER}.
     *
     * @param n      the third flattening
     * @param auxin  the input auxiliary latitude
     * @param auxout the output auxiliary latitude
     * @return the {@value #ORDER} Fourier coefficients
     */
    public static double[] coeffs(double n, int auxin, int auxout) {
        double[] f = new double[ORDER];
        coeffs(n, auxin, auxout, f);
        return f;
    }

    /**
     * Reports whether the given conversion has a tabulated coefficient matrix.
     *
     * @param auxin  the input auxiliary latitude
     * @param auxout the output auxiliary latitude
     * @return true if {@link #coeffs(double, int, int, double[])} will succeed
     */
    public static boolean isSupported(int auxin, int auxout) {
        if (!(auxin >= 0 && auxin < NUMBER && auxout >= 0 && auxout < NUMBER)) {
            return false;
        }
        final int k = NUMBER * auxout + auxin;
        return PTRS[k] != PTRS[k + 1];
    }

    /**
     * Evaluates {@code sum(p[offset + i] * x^i, i, 0, n)} by Horner's method.
     * Port of {@code pj_polyval}; note {@code p} holds {@code n + 1} usable elements
     * from {@code offset}, and {@code n < 0} yields 0.
     *
     * @param x      the argument
     * @param p      the coefficient array
     * @param offset index in {@code p} of the constant term
     * @param n      the degree
     * @return the polynomial value
     */
    public static double polyval(double x, double[] p, int offset, int n) {
        double y = n < 0 ? 0.0 : p[offset + n];
        for (; n > 0; ) {
            y = y * x + p[offset + --n];
        }
        return y;
    }

    /**
     * Evaluates {@code sum(p[i] * x^i, i, 0, p.length - 1)} by Horner's method.
     *
     * @param x the argument
     * @param p the coefficient array, constant term first
     * @return the polynomial value
     */
    public static double polyval(double x, double[] p) {
        return polyval(x, p, 0, p.length - 1);
    }

    /**
     * The rectifying radius, {@code (quarter meridian) / ((pi/2) * a)}. Port of
     * {@code pj_rectifying_radius}: the expansion of
     * {@code (quarter meridian) / ((a+b)/2 * pi/2)} as a series in {@code n^2},
     * divided by {@code 1 + n}. Its accuracy matches the auxiliary-latitude series.
     *
     * @param n the third flattening
     * @return the rectifying radius, in units of the semi-major axis
     */
    public static double rectifyingRadius(double n) {
        return polyval(n * n, COEFF_RAD, 0, 3) / (1.0 + n);
    }

    /**
     * The third flattening {@code n = (a - b) / (a + b)} derived from the squared
     * first eccentricity.
     *
     * <p>Upstream ({@code ell_set.cpp:550-630}) computes {@code n = pow(tan(alpha/2), 2)}
     * with {@code alpha = asin(e)} — three platform-dependent libm calls. Since
     * {@code tan(alpha/2) = e / (1 + sqrt(1 - e^2))} exactly, this equals
     * {@code es / (1 + sqrt(1 - es))^2}, computed here with a single exactly-rounded
     * {@code sqrt}. The deviation is at most 2 ulp on {@code n}, propagating to about
     * 1e-19 rad, forty orders of magnitude inside the tightest conformance bar; in
     * exchange every derived coefficient becomes bit-reproducible across x86-64 and
     * AArch64, which cannot be achieved any other way.
     *
     * @param es the squared first eccentricity
     * @return the third flattening
     */
    public static double thirdFlattening(double es) {
        final double t = 1.0 + Math.sqrt(1.0 - es);
        return es / (t * t);
    }

    private static String name(int aux) {
        switch (aux) {
            case GEOGRAPHIC: return "GEOGRAPHIC(phi)";
            case PARAMETRIC: return "PARAMETRIC(beta)";
            case GEOCENTRIC: return "GEOCENTRIC(theta)";
            case RECTIFYING: return "RECTIFYING(mu)";
            case CONFORMAL:  return "CONFORMAL(chi)";
            case AUTHALIC:   return "AUTHALIC(xi)";
            default:         return "UNKNOWN(" + aux + ")";
        }
    }
}
