/*******************************************************************************
 * Copyright 2026
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *******************************************************************************/

package org.locationtech.proj4j.util;

/**
 * Allocation-free {@code sin}, {@code cos} and {@code tan} that are
 * <strong>bit-identical to {@link StrictMath}</strong> on every {@code double} input.
 *
 * <h2>Why this class exists</h2>
 *
 * proj4j needs fdlibm trigonometry, not platform trigonometry, for two independent reasons:
 *
 * <ul>
 *   <li><em>Conformance.</em> PROJ's {@code gie} corpus was generated by an fdlibm-equivalent
 *       {@code sin}. In the adams family the conditioning amplifies a 1-ulp {@code sin}
 *       difference by ~3e8: at {@code +proj=adams_ws2 +ellps=WGS84} and {@code (179.999, 0)},
 *       {@code Math.sin(lam/2)} yields {@code x = 16686159.3838 m} (27.8 mm outside a 1 mm bar)
 *       while {@code StrictMath.sin(lam/2)} yields {@code 16686159.3563 m} (0.35 mm inside it).
 *       Neither is the more accurate — the exact value, {@code 16686159.3639 m}, sits between
 *       them. fdlibm wins on <em>fidelity</em>, not accuracy.</li>
 *   <li><em>Determinism.</em> {@code Math.sin/cos/tan} are {@code @IntrinsicCandidate}; HotSpot
 *       substitutes a platform-specific implementation, so results differ across architectures
 *       and, at the margin, across JIT tiers. fdlibm is pure Java and identical everywhere.</li>
 * </ul>
 *
 * But {@code StrictMath.sin/cos/tan} <strong>allocate</strong> from JDK 21 onward — <b>21, not
 * 17</b>. The JDK's port of fdlibm from C to Java ran over several releases and reached
 * {@code sin}/{@code cos}/{@code tan} only in 21; through JDK 17 they are still {@code native}
 * JNI calls into compiled fdlibm, which allocate no Java object at all. (JEP 306, in 17, restored
 * always-strict floating-point semantics; it did not port these three.) Verified by reflection and
 * by {@code jimage}: {@code Modifier.isNative(StrictMath.sin)} is {@code true} on Corretto and
 * Temurin 17.0.20 and {@code false} on 21/25/26, and {@code java.lang.FdLibm$Sin} is <em>absent</em>
 * from a JDK 17 image (which ships five {@code FdLibm} nested classes — {@code Cbrt Exp Hypot Pow}
 * plus the outer — against 21's twenty-three). From 21,
 * {@code java.lang.FdLibm.Sin/Cos/Tan.compute} each begin with {@code new double[2]} to receive
 * the two-word result of argument reduction — a C out-parameter idiom that escape analysis does
 * not remove, because the array is passed to {@code RemPio2.__ieee754_rem_pio2}, which is far too
 * large to inline. {@code __ieee754_rem_pio2} then unconditionally allocates a {@code double[3]},
 * and its multi-word path allocates an {@code int[20]} and three {@code double[20]} more. So the
 * cost is tiered, measured on Temurin 21.0.11 and unchanged on OpenJDK 26.0.2 — and
 * <strong>flatly 0 B/op on 8 through 17</strong>, at every optimisation level, because there is no
 * Java object there to allocate:
 *
 * <table>
 *   <caption>{@code StrictMath.sin} allocation by argument magnitude, <b>JDK &gt;= 21 only</b></caption>
 *   <tr><th>argument</th><th>arrays</th><th>B/op</th></tr>
 *   <tr><td>{@code |x| <= pi/4}</td><td>{@code double[2]}</td><td>32</td></tr>
 *   <tr><td>{@code pi/4 < |x| <= 2^19*(pi/2)}</td><td>{@code + double[3]}</td><td>72</td></tr>
 *   <tr><td>{@code |x| > 2^19*(pi/2)}</td><td>{@code + int[20] + 3 x double[20]}</td><td>696</td></tr>
 * </table>
 *
 * <p>A longitude in radians spans {@code +/-pi}, so three quarters of a realistic
 * {@code sin(lam)} workload takes the reduction path and the effective figure is
 * <strong>62 B/op</strong>, not the 32 B/op that a survey confined to {@code |x| <= pi/4}
 * reports. Measured in a loop shaped like an ellipsoidal transverse Mercator forward — eight trig
 * calls per point — C2 removes none of it: <strong>483 B per vertex</strong>, or 46 MB of garbage
 * per 100,000-vertex geometry, per row, in a Spark executor. This class measures 0 B/op in the
 * same loop.
 *
 * <p>{@code exp}, {@code log}, {@code atan}, {@code atan2}, {@code asin}, {@code acos},
 * {@code log1p}, {@code sinh}, {@code cosh}, {@code hypot} and {@code sqrt} allocate nothing.
 * {@code StrictMath.pow}'s general path allocates 96 B/op on Temurin 21 (three
 * {@code final double[2]} locals, {@code BP}/{@code DP_H}/{@code DP_L}) but 0 on OpenJDK 26, so
 * it is fixed upstream. {@code sin}, {@code cos} and {@code tan} are not fixed on either.
 *
 * <h2>What this class does</h2>
 *
 * The algorithm is JDK 21's {@code java.lang.FdLibm.Sin}, {@code Cos}, {@code Tan},
 * {@code RemPio2} and {@code KernelRemPio2}, transcribed literally — the same polynomial
 * coefficients, the same expression nesting, the same branch thresholds, the same
 * {@code Math.scalb}/{@code Math.floor}/{@code Math.abs} calls. Only the plumbing changed:
 *
 * <ul>
 *   <li>The {@code double[2]} out-parameter is gone. Argument reduction and kernel evaluation
 *       are fused into one method, {@link #reduceAndKernel}, so the reduced pair {@code (y0, y1)}
 *       lives in local scalars and never needs a carrier.</li>
 *   <li>The multi-word path for {@code |x| > 2^19 * (pi/2)} genuinely needs arrays
 *       ({@code __kernel_rem_pio2} does 24-bit-limb arithmetic over a dynamically sized
 *       window), so it takes them from a reusable {@link Scratch}. That path is unreachable for
 *       any angle in radians a coordinate transform can produce; it is supported only so the
 *       bit-identity claim holds for <em>every</em> input, including {@code Double.MAX_VALUE}.</li>
 *   <li>The unused {@code prec} settings of {@code __kernel_rem_pio2} are dropped;
 *       {@code sin}/{@code cos}/{@code tan} only ever call it with {@code prec == 2}, fixing
 *       {@code jk == 4}.</li>
 * </ul>
 *
 * The reduced-argument dispatch table, unchanged from fdlibm, with {@code n = k mod 4} for
 * {@code y = x - k*pi/2}:
 *
 * <pre>
 *      n        sin(x)      cos(x)        tan(x)
 * ----------------------------------------------------
 *      0          S           C             T
 *      1          C          -S            -1/T
 *      2         -S          -C             T
 *      3         -C           S            -1/T
 * </pre>
 *
 * <h2>Guarantees</h2>
 *
 * <ul>
 *   <li>{@code Double.doubleToRawLongBits(sin(x)) == Double.doubleToRawLongBits(StrictMath.sin(x))}
 *       for every {@code double x}, including subnormals, {@code +/-0.0} (sign preserved),
 *       {@code +/-Infinity} (NaN out) and NaN (payload preserved through {@code x - x}).
 *       Verified over ~235,000,000 raw-bit comparisons on Temurin 21.0.11 and 90,000,000 on
 *       OpenJDK 26.0.2, with zero mismatches; for contrast, {@code Math.sin} differs from
 *       {@code StrictMath.sin} on 7.27% of arguments drawn uniformly from {@code [-4pi, 4pi]}.</li>
 *   <li>Zero allocation for every finite input, with the single exception of the first
 *       {@code |x| > 2^19 * (pi/2)} call on a given thread, which materialises that thread's
 *       {@link Scratch}. Use the {@link Scratch}-taking overloads to make the guarantee
 *       unconditional.</li>
 *   <li>Thread-safe and reentrant: no mutable static state, and each thread's {@link Scratch}
 *       is private to it.</li>
 * </ul>
 *
 * <p>{@code strictfp} is redundant from Java 17 (JEP 306) but is free and removes the question
 * on an 8/11 baseline, where an x87 FPU could otherwise evaluate intermediates in 80-bit
 * extended precision.
 *
 * @see StrictMath#sin(double)
 */
public final strictfp class FastStrictTrig {

    private FastStrictTrig() {
        throw new UnsupportedOperationException();
    }

    // ------------------------------------------------------------------
    // Bit-manipulation helpers (FdLibm.__HI / __LO / __HI_LO, verbatim)
    // ------------------------------------------------------------------

    /*
     * Masks for the high-order 32 bits of an IEEE 754 double: 1 sign bit, then 11 exponent bits,
     * then the top 20 significand bits.
     */
    private static final int EXP_BITS = 0x7ff0_0000;
    private static final int EXP_SIGNIF_BITS = 0x7fff_ffff;

    private static final double TWO24 = 0x1.0p24;

    /** Low-order 32 bits of the argument as an int. */
    private static int __LO(double x) {
        return (int) Double.doubleToRawLongBits(x);
    }

    /** {@code x}'s high bits with {@code low} as the low bits. */
    private static double __LO(double x, int low) {
        long transX = Double.doubleToRawLongBits(x);
        return Double.longBitsToDouble((transX & 0xFFFF_FFFF_0000_0000L)
                | (low & 0x0000_0000_FFFF_FFFFL));
    }

    /** High-order 32 bits of the argument as an int. */
    private static int __HI(double x) {
        return (int) (Double.doubleToRawLongBits(x) >> 32);
    }

    /** {@code x}'s low bits with {@code high} as the high bits. */
    private static double __HI(double x, int high) {
        long transX = Double.doubleToRawLongBits(x);
        return Double.longBitsToDouble((transX & 0x0000_0000_FFFF_FFFFL)
                | (((long) high) << 32));
    }

    /** A double assembled from a high and a low word. */
    private static double __HI_LO(int high, int low) {
        return Double.longBitsToDouble(((long) high << 32) | (low & 0xffff_ffffL));
    }

    // ------------------------------------------------------------------
    // Public API
    // ------------------------------------------------------------------

    /**
     * Returns the sine of an angle in radians, bit-identical to {@link StrictMath#sin(double)}.
     * Allocation-free.
     *
     * @param x an angle, in radians
     * @return the sine of {@code x}, bit-for-bit as {@link StrictMath#sin(double)} would return it
     */
    public static double sin(double x) {
        final int ix = __HI(x) & EXP_SIGNIF_BITS;
        if (ix <= 0x3fe9_21fb) {          // |x| ~< pi/4
            return kernelSin(x, 0.0, 0);
        } else if (ix >= EXP_BITS) {      // sin(Inf or NaN) is NaN
            return x - x;
        }
        return reduceAndKernel(x, ix, OP_SIN, null);
    }

    /**
     * Returns the cosine of an angle in radians, bit-identical to
     * {@link StrictMath#cos(double)}. Allocation-free.
     *
     * @param x an angle, in radians
     * @return the cosine of {@code x}, bit-for-bit as {@link StrictMath#cos(double)} would return it
     */
    public static double cos(double x) {
        final int ix = __HI(x) & EXP_SIGNIF_BITS;
        if (ix <= 0x3fe9_21fb) {          // |x| ~< pi/4
            return kernelCos(x, 0.0);
        } else if (ix >= EXP_BITS) {      // cos(Inf or NaN) is NaN
            return x - x;
        }
        return reduceAndKernel(x, ix, OP_COS, null);
    }

    /**
     * Returns the tangent of an angle in radians, bit-identical to
     * {@link StrictMath#tan(double)}. Allocation-free.
     *
     * @param x an angle, in radians
     * @return the tangent of {@code x}, bit-for-bit as {@link StrictMath#tan(double)} would return it
     */
    public static double tan(double x) {
        final int ix = __HI(x) & EXP_SIGNIF_BITS;
        if (ix <= 0x3fe9_21fb) {          // |x| ~< pi/4
            return kernelTan(x, 0.0, 1);
        } else if (ix >= EXP_BITS) {      // tan(Inf or NaN) is NaN
            return x - x;
        }
        return reduceAndKernel(x, ix, OP_TAN, null);
    }

    /**
     * As {@link #sin(double)}, but taking the caller's {@link Scratch} instead of a thread-local
     * one. Allocation-free for every input with no warm-up caveat.
     *
     * @param x       an angle, in radians
     * @param scratch reusable working storage; must not be shared between threads. May be
     *                {@code null}, in which case a thread-local instance is used if needed.
     * @return the sine of {@code x}, bit-for-bit as {@link StrictMath#sin(double)} would return it
     */
    public static double sin(double x, Scratch scratch) {
        final int ix = __HI(x) & EXP_SIGNIF_BITS;
        if (ix <= 0x3fe9_21fb) {
            return kernelSin(x, 0.0, 0);
        } else if (ix >= EXP_BITS) {
            return x - x;
        }
        return reduceAndKernel(x, ix, OP_SIN, scratch);
    }

    /**
     * As {@link #cos(double)}, but taking the caller's {@link Scratch}.
     *
     * @param x       an angle, in radians
     * @param scratch reusable working storage; must not be shared between threads. May be
     *                {@code null}.
     * @return the cosine of {@code x}, bit-for-bit as {@link StrictMath#cos(double)} would return it
     */
    public static double cos(double x, Scratch scratch) {
        final int ix = __HI(x) & EXP_SIGNIF_BITS;
        if (ix <= 0x3fe9_21fb) {
            return kernelCos(x, 0.0);
        } else if (ix >= EXP_BITS) {
            return x - x;
        }
        return reduceAndKernel(x, ix, OP_COS, scratch);
    }

    /**
     * As {@link #tan(double)}, but taking the caller's {@link Scratch}.
     *
     * @param x       an angle, in radians
     * @param scratch reusable working storage; must not be shared between threads. May be
     *                {@code null}.
     * @return the tangent of {@code x}, bit-for-bit as {@link StrictMath#tan(double)} would return it
     */
    public static double tan(double x, Scratch scratch) {
        final int ix = __HI(x) & EXP_SIGNIF_BITS;
        if (ix <= 0x3fe9_21fb) {
            return kernelTan(x, 0.0, 1);
        } else if (ix >= EXP_BITS) {
            return x - x;
        }
        return reduceAndKernel(x, ix, OP_TAN, scratch);
    }

    /**
     * Reusable working storage for the multi-word argument-reduction path, which is entered only
     * for {@code |x| > 2^19 * (pi/2)} (about 823550 radians). A {@code Scratch} is
     * <strong>not thread-safe</strong>; give each thread its own, or pass {@code null} and let
     * the thread-local one be used.
     *
     * <p>Allocating one costs about 550 bytes. A transform kernel that wants a hard
     * zero-allocation guarantee over untrusted input should hold one per worker and pass it to
     * the {@link #sin(double, Scratch)} family.
     */
    public static final class Scratch {

        /** Creates working storage, ready for immediate use. */
        public Scratch() {
        }

        // FdLibm.RemPio2.__ieee754_rem_pio2's `double[] tx = new double[3]`
        final double[] tx = new double[3];
        // FdLibm.KernelRemPio2.__kernel_rem_pio2's four length-20 working arrays
        final int[] iq = new int[20];
        final double[] f = new double[20];
        final double[] fq = new double[20];
        final double[] q = new double[20];
        // stands in for the `double[] y` out-parameter
        double y0;
        double y1;
    }

    private static final ThreadLocal<Scratch> SCRATCH = new ThreadLocal<Scratch>() {
        @Override
        protected Scratch initialValue() {
            return new Scratch();
        }
    };

    // ------------------------------------------------------------------
    // Fused argument reduction + kernel evaluation
    // ------------------------------------------------------------------

    private static final int OP_SIN = 0;
    private static final int OP_COS = 1;
    private static final int OP_TAN = 2;

    /*
     * invpio2:  53 bits of 2/pi
     * pio2_1:   first  33 bit of pi/2      pio2_1t: pi/2 - pio2_1
     * pio2_2:   second 33 bit of pi/2      pio2_2t: pi/2 - (pio2_1+pio2_2)
     * pio2_3:   third  33 bit of pi/2      pio2_3t: pi/2 - (pio2_1+pio2_2+pio2_3)
     */
    private static final double
            INVPIO2 = 0x1.45f306dc9c883p-1,   // 6.36619772367581382433e-01
            PIO2_1 = 0x1.921fb544p0,          // 1.57079632673412561417e+00
            PIO2_1T = 0x1.0b4611a626331p-34,  // 6.07710050650619224932e-11
            PIO2_2 = 0x1.0b4611a6p-34,        // 6.07710050630396597660e-11
            PIO2_2T = 0x1.3198a2e037073p-69,  // 2.02226624879595063154e-21
            PIO2_3 = 0x1.3198a2ep-69,         // 2.02226624871116645580e-21
            PIO2_3T = 0x1.b839a252049c1p-104; // 8.47842766036889956997e-32

    private static final int[] NPIO2_HW = {
            0x3FF921FB, 0x400921FB, 0x4012D97C, 0x401921FB, 0x401F6A7A, 0x4022D97C,
            0x4025FDBB, 0x402921FB, 0x402C463A, 0x402F6A7A, 0x4031475C, 0x4032D97C,
            0x40346B9C, 0x4035FDBB, 0x40378FDB, 0x403921FB, 0x403AB41B, 0x403C463A,
            0x403DD85A, 0x403F6A7A, 0x40407E4C, 0x4041475C, 0x4042106C, 0x4042D97C,
            0x4043A28C, 0x40446B9C, 0x404534AC, 0x4045FDBB, 0x4046C6CB, 0x40478FDB,
            0x404858EB, 0x404921FB,
    };

    /**
     * The body of {@code FdLibm.RemPio2.__ieee754_rem_pio2} with the {@code double[] y}
     * out-parameter replaced by locals, followed immediately by the kernel selection that
     * {@code Sin/Cos/Tan.compute} would have performed on {@code y}.
     *
     * <p>Precondition, guaranteed by every caller: {@code 0x3fe921fb < ix < EXP_BITS}, i.e.
     * {@code x} is finite and {@code |x|} is greater than about {@code pi/4}. The two checks
     * that fdlibm repeats here are therefore dead and have been dropped.
     *
     * @param ix high word of {@code |x|}
     * @param op one of {@link #OP_SIN}, {@link #OP_COS}, {@link #OP_TAN}
     */
    private static double reduceAndKernel(double x, int ix, int op, Scratch scratch) {
        final int hx = __HI(x);
        double z, w, t, r, fn;
        double y0, y1;
        int i, j, n;

        if (ix < 0x4002_d97c) {  // |x| < 3pi/4, special case with n = +-1
            if (hx > 0) {
                z = x - PIO2_1;
                if (ix != 0x3ff9_21fb) {   // 33+53 bit pi is good enough
                    y0 = z - PIO2_1T;
                    y1 = (z - y0) - PIO2_1T;
                } else {                   // near pi/2, use 33+33+53 bit pi
                    z -= PIO2_2;
                    y0 = z - PIO2_2T;
                    y1 = (z - y0) - PIO2_2T;
                }
                n = 1;
            } else {                       // negative x
                z = x + PIO2_1;
                if (ix != 0x3ff9_21fb) {   // 33+53 bit pi is good enough
                    y0 = z + PIO2_1T;
                    y1 = (z - y0) + PIO2_1T;
                } else {                   // near pi/2, use 33+33+53 bit pi
                    z += PIO2_2;
                    y0 = z + PIO2_2T;
                    y1 = (z - y0) + PIO2_2T;
                }
                n = -1;
            }
            return kernel(op, n, y0, y1);
        }

        if (ix <= 0x4139_21fb) { // |x| ~<= 2^19*(pi/2), medium size
            t = Math.abs(x);
            n = (int) (t * INVPIO2 + 0.5);
            fn = (double) n;
            r = t - fn * PIO2_1;
            w = fn * PIO2_1T;    // 1st round good to 85 bit
            if (n < 32 && ix != NPIO2_HW[n - 1]) {
                y0 = r - w;      // quick check no cancellation
            } else {
                j = ix >> 20;
                y0 = r - w;
                i = j - ((__HI(y0) >> 20) & 0x7ff);
                if (i > 16) {    // 2nd iteration needed, good to 118
                    t = r;
                    w = fn * PIO2_2;
                    r = t - w;
                    w = fn * PIO2_2T - ((t - r) - w);
                    y0 = r - w;
                    i = j - ((__HI(y0) >> 20) & 0x7ff);
                    if (i > 49) { // 3rd iteration needed, 151 bits acc
                        t = r;    // will cover all possible cases
                        w = fn * PIO2_3;
                        r = t - w;
                        w = fn * PIO2_3T - ((t - r) - w);
                        y0 = r - w;
                    }
                }
            }
            y1 = (r - y0) - w;
            if (hx < 0) {
                y0 = -y0;
                y1 = -y1;
                n = -n;
            }
            return kernel(op, n, y0, y1);
        }

        /*
         * All other (large) arguments. fdlibm handles Inf/NaN here; the public entry points
         * already did, so only the multi-word path remains.
         */
        final Scratch s = (scratch != null) ? scratch : SCRATCH.get();
        final double[] tx = s.tx;

        // set z = scalbn(|x|, ilogb(x) - 23)
        z = 0.0;
        z = __LO(z, __LO(x));
        final int e0 = (ix >> 20) - 1046;   // e0 = ilogb(z) - 23
        z = __HI(z, ix - (e0 << 20));
        for (i = 0; i < 2; i++) {
            tx[i] = (double) ((int) (z));
            z = (z - tx[i]) * TWO24;
        }
        tx[2] = z;
        int nx = 3;
        while (tx[nx - 1] == 0.0) {         // skip zero term
            nx--;
        }
        n = kernelRemPio2(tx, e0, nx, s);
        y0 = s.y0;
        y1 = s.y1;
        if (hx < 0) {
            y0 = -y0;
            y1 = -y1;
            n = -n;
        }
        return kernel(op, n, y0, y1);
    }

    /**
     * fdlibm's post-reduction dispatch: the {@code switch (n & 3)} in {@code Sin.compute} and
     * {@code Cos.compute}, and the {@code 1 - ((n & 1) << 1)} sign in {@code Tan.compute}.
     */
    private static double kernel(int op, int n, double y0, double y1) {
        if (op == OP_TAN) {
            return kernelTan(y0, y1, 1 - ((n & 1) << 1)); // 1 -- n even; -1 -- n odd
        }
        final boolean isSin = (op == OP_SIN);
        switch (n & 3) {
            case 0:
                return isSin ? kernelSin(y0, y1, 1) : kernelCos(y0, y1);
            case 1:
                return isSin ? kernelCos(y0, y1) : -kernelSin(y0, y1, 1);
            case 2:
                return isSin ? -kernelSin(y0, y1, 1) : -kernelCos(y0, y1);
            default:
                return isSin ? -kernelCos(y0, y1) : kernelSin(y0, y1, 1);
        }
    }

    // ------------------------------------------------------------------
    // FdLibm.Sin.__kernel_sin
    // ------------------------------------------------------------------

    private static final double
            S1 = -0x1.5555555555549p-3,  // -1.66666666666666324348e-01
            S2 = 0x1.111111110f8a6p-7,   //  8.33333333332248946124e-03
            S3 = -0x1.a01a019c161d5p-13, // -1.98412698298579493134e-04
            S4 = 0x1.71de357b1fe7dp-19,  //  2.75573137070700676789e-06
            S5 = -0x1.ae5e68a2b9cebp-26, // -2.50507602534068634195e-08
            S6 = 0x1.5d93a5acfd57cp-33;  //  1.58969099521155010221e-10

    /**
     * Kernel sine on {@code [-pi/4, pi/4]}. {@code y} is the tail of {@code x}; {@code iy == 0}
     * means the tail is zero.
     */
    private static double kernelSin(double x, double y, int iy) {
        double z, r, v;
        int ix;
        ix = __HI(x) & EXP_SIGNIF_BITS;    // high word of x
        if (ix < 0x3e40_0000) {            // |x| < 2**-27
            if ((int) x == 0)              // generate inexact
                return x;
        }
        z = x * x;
        v = z * x;
        r = S2 + z * (S3 + z * (S4 + z * (S5 + z * S6)));
        if (iy == 0) {
            return x + v * (S1 + z * r);
        } else {
            return x - ((z * (0.5 * y - v * r) - y) - v * S1);
        }
    }

    // ------------------------------------------------------------------
    // FdLibm.Cos.__kernel_cos
    // ------------------------------------------------------------------

    private static final double
            C1 = 0x1.555555555554cp-5,   //  4.16666666666666019037e-02
            C2 = -0x1.6c16c16c15177p-10, // -1.38888888888741095749e-03
            C3 = 0x1.a01a019cb159p-16,   //  2.48015872894767294178e-05
            C4 = -0x1.27e4f809c52adp-22, // -2.75573143513906633035e-07
            C5 = 0x1.1ee9ebdb4b1c4p-29,  //  2.08757232129817482790e-09
            C6 = -0x1.8fae9be8838d4p-37; // -1.13596475577881948265e-11

    /** Kernel cosine on {@code [-pi/4, pi/4]}. {@code y} is the tail of {@code x}. */
    private static double kernelCos(double x, double y) {
        double a, hz, z, r, qx;
        int ix;
        ix = __HI(x) & EXP_SIGNIF_BITS;   // ix = |x|'s high word
        if (ix < 0x3e40_0000) {           // if x < 2**-27
            if (((int) x) == 0) {         // generate inexact
                return 1.0;
            }
        }
        z = x * x;
        r = z * (C1 + z * (C2 + z * (C3 + z * (C4 + z * (C5 + z * C6)))));
        if (ix < 0x3FD3_3333) {           // if |x| < 0.3
            return 1.0 - (0.5 * z - (z * r - x * y));
        } else {
            if (ix > 0x3fe9_0000) {       // x > 0.78125
                qx = 0.28125;
            } else {
                qx = __HI_LO(ix - 0x0020_0000, 0);
            }
            hz = 0.5 * z - qx;
            a = 1.0 - qx;
            return a - (hz - (z * r - x * y));
        }
    }

    // ------------------------------------------------------------------
    // FdLibm.Tan.__kernel_tan
    // ------------------------------------------------------------------

    private static final double
            PIO4 = 0x1.921fb54442d18p-1,  // 7.85398163397448278999e-01
            PIO4LO = 0x1.1a62633145c07p-55; // 3.06161699786838301793e-17

    /*
     * FdLibm's T[0..12], unrolled into named constants: the coefficients are used at fixed
     * indices only, so the array (and its bounds checks) buy nothing.
     */
    private static final double
            T0 = 0x1.5555555555563p-2,   //  3.33333333333334091986e-01
            T1 = 0x1.111111110fe7ap-3,   //  1.33333333333201242699e-01
            T2 = 0x1.ba1ba1bb341fep-5,   //  5.39682539762260521377e-02
            T3 = 0x1.664f48406d637p-6,   //  2.18694882948595424599e-02
            T4 = 0x1.226e3e96e8493p-7,   //  8.86323982359930005737e-03
            T5 = 0x1.d6d22c9560328p-9,   //  3.59207910759131235356e-03
            T6 = 0x1.7dbc8fee08315p-10,  //  1.45620945432529025516e-03
            T7 = 0x1.344d8f2f26501p-11,  //  5.88041240820264096874e-04
            T8 = 0x1.026f71a8d1068p-12,  //  2.46463134818469906812e-04
            T9 = 0x1.47e88a03792a6p-14,  //  7.81794442939557092300e-05
            T10 = 0x1.2b80f32f0a7e9p-14, //  7.14072491382608190305e-05
            T11 = -0x1.375cbdb605373p-16, // -1.85586374855275456654e-05
            T12 = 0x1.b2a7074bf7ad4p-16; //  2.59073051863633712884e-05

    /**
     * Kernel tangent on {@code [-pi/4, pi/4]}. {@code y} is the tail of {@code x};
     * {@code iy == 1} returns {@code tan}, {@code iy == -1} returns {@code -1/tan}.
     */
    private static double kernelTan(double x, double y, int iy) {
        double z, r, v, w, s;
        int ix, hx;
        hx = __HI(x);                  // high word of x
        ix = hx & EXP_SIGNIF_BITS;     // high word of |x|
        if (ix < 0x3e30_0000) {        // x < 2**-28
            if ((int) x == 0) {        // generate inexact
                if (((ix | __LO(x)) | (iy + 1)) == 0) {
                    return 1.0 / Math.abs(x);
                } else {
                    if (iy == 1) {
                        return x;
                    } else {           // compute -1 / (x+y) carefully
                        double a, t;

                        z = w = x + y;
                        z = __LO(z, 0);
                        v = y - (z - x);
                        t = a = -1.0 / w;
                        t = __LO(t, 0);
                        s = 1.0 + t * z;
                        return t + a * (s + t * v);
                    }
                }
            }
        }
        if (ix >= 0x3FE5_9428) {       // |x| >= 0.6744
            if (hx < 0) {
                x = -x;
                y = -y;
            }
            z = PIO4 - x;
            w = PIO4LO - y;
            x = z + w;
            y = 0.0;
        }
        z = x * x;
        w = z * z;
        /*
         * Break x^5*(T[1]+x^2*T[2]+...) into
         *    x^5(T[1]+x^4*T[3]+...+x^20*T[11]) +
         *    x^5(x^2*(T[2]+x^4*T[4]+...+x^22*[T12]))
         */
        r = T1 + w * (T3 + w * (T5 + w * (T7 + w * (T9 + w * T11))));
        v = z * (T2 + w * (T4 + w * (T6 + w * (T8 + w * (T10 + w * T12)))));
        s = z * x;
        r = y + z * (s * (r + v) + y);
        r += T0 * s;
        w = x + r;
        if (ix >= 0x3FE5_9428) {
            v = (double) iy;
            return (double) (1 - ((hx >> 30) & 2)) * (v - 2.0 * (x - (w * w / (w + v) - r)));
        }
        if (iy == 1) {
            return w;
        } else {
            /*
             * If an error of up to 2 ulp were allowed this could simply return -1.0/(x + r);
             * instead compute -1.0/(x + r) accurately.
             */
            double a, t;
            z = w;
            z = __LO(z, 0);
            v = r - (z - x);   // z + v = r + x
            t = a = -1.0 / w;  // a = -1.0/w
            t = __LO(t, 0);
            s = 1.0 + t * z;
            return t + a * (s + t * v);
        }
    }

    // ------------------------------------------------------------------
    // FdLibm.KernelRemPio2.__kernel_rem_pio2, specialised to prec == 2
    // ------------------------------------------------------------------

    /** 396 hex digits (476 decimal) of 2/pi, in 24-bit limbs. */
    private static final int[] TWO_OVER_PI = {
            0xA2F983, 0x6E4E44, 0x1529FC, 0x2757D1, 0xF534DD, 0xC0DB62,
            0x95993C, 0x439041, 0xFE5163, 0xABDEBB, 0xC561B7, 0x246E3A,
            0x424DD2, 0xE00649, 0x2EEA09, 0xD1921C, 0xFE1DEB, 0x1CB129,
            0xA73EE8, 0x8235F5, 0x2EBB44, 0x84E99C, 0x7026B4, 0x5F7E41,
            0x3991D6, 0x398353, 0x39F49C, 0x845F8B, 0xBDF928, 0x3B1FF8,
            0x97FFDE, 0x05980F, 0xEF2F11, 0x8B5A0A, 0x6D1F6D, 0x367ECF,
            0x27CB09, 0xB74F46, 0x3F669E, 0x5FEA2D, 0x7527BA, 0xC7EBE5,
            0xF17B3D, 0x0739F7, 0x8A5292, 0xEA6BFB, 0x5FB11F, 0x8D5D08,
            0x560330, 0x46FC7B, 0x6BABF0, 0xCFBC20, 0x9AF436, 0x1DA9E3,
            0x91615E, 0xE61B08, 0x659985, 0x5F14A0, 0x68408D, 0xFFD880,
            0x4D7327, 0x310606, 0x1556CA, 0x73A8C9, 0x60E27B, 0xC08C6B,
    };

    /** pi/2 cut into 24-bit chunks. */
    private static final double[] PIO2 = {
            0x1.921fb4p0,    // 1.57079625129699707031e+00
            0x1.4442dp-24,   // 7.54978941586159635335e-08
            0x1.846988p-48,  // 5.39030252995776476554e-15
            0x1.8cc516p-72,  // 3.28200341580791294123e-22
            0x1.01b838p-96,  // 1.27065575308067607349e-29
            0x1.a25204p-120, // 1.22933308981111328932e-36
            0x1.382228p-145, // 2.73370053816464559624e-44
            0x1.9f31dp-169,  // 2.16741683877804819444e-51
    };

    private static final double TWON24 = 0x1.0p-24;

    /**
     * {@code __kernel_rem_pio2} with {@code prec} fixed at 2 (the only value
     * {@code sin}/{@code cos}/{@code tan} use, giving {@code jk = init_jk[2] = 4}), its four
     * length-20 working arrays taken from {@code s}, and its {@code double[] y} out-parameter
     * written to {@code s.y0} / {@code s.y1}.
     *
     * <p>Every index read in a call is written earlier in that same call, so the arrays need no
     * clearing between calls. In particular {@code f}, {@code q} and {@code iq} are filled to at
     * least {@code jz} before the summation loops read them, and the {@code iq[jz]} read after
     * the distillation loop follows either a decrement of {@code jz} or an assignment.
     *
     * @return {@code n & 7}, the last three digits of {@code N} in {@code y = x - N*pi/2}
     */
    private static int kernelRemPio2(double[] x, int e0, int nx, Scratch s) {
        int jz, jx, jv, jp, jk, carry, n, i, j, k, m, q0, ih;
        double z, fw;
        final int[] iq = s.iq;
        final double[] f = s.f;
        final double[] fq = s.fq;
        final double[] q = s.q;

        // initialize jk
        jk = 4;   // == init_jk[prec] for prec == 2
        jp = jk;

        // determine jx, jv, q0, note that 3 > q0
        jx = nx - 1;
        jv = (e0 - 3) / 24;
        if (jv < 0) {
            jv = 0;
        }
        q0 = e0 - 24 * (jv + 1);

        // set up f[0] to f[jx+jk] where f[jx+jk] = ipio2[jv+jk]
        j = jv - jx;
        m = jx + jk;
        for (i = 0; i <= m; i++, j++) {
            f[i] = (j < 0) ? 0.0 : (double) TWO_OVER_PI[j];
        }

        // compute q[0],q[1],...q[jk]
        for (i = 0; i <= jk; i++) {
            for (j = 0, fw = 0.0; j <= jx; j++) {
                fw += x[j] * f[jx + i - j];
            }
            q[i] = fw;
        }

        jz = jk;
        while (true) {
            // distill q[] into iq[] reversingly
            for (i = 0, j = jz, z = q[jz]; j > 0; i++, j--) {
                fw = (double) ((int) (TWON24 * z));
                iq[i] = (int) (z - TWO24 * fw);
                z = q[j - 1] + fw;
            }

            // compute n
            z = Math.scalb(z, q0);               // actual value of z
            z -= 8.0 * Math.floor(z * 0.125);    // trim off integer >= 8
            n = (int) z;
            z -= (double) n;
            ih = 0;
            if (q0 > 0) {      // need iq[jz - 1] to determine n
                i = (iq[jz - 1] >> (24 - q0));
                n += i;
                iq[jz - 1] -= i << (24 - q0);
                ih = iq[jz - 1] >> (23 - q0);
            } else if (q0 == 0) {
                ih = iq[jz - 1] >> 23;
            } else if (z >= 0.5) {
                ih = 2;
            }

            if (ih > 0) {      // q > 0.5
                n += 1;
                carry = 0;
                for (i = 0; i < jz; i++) {        // compute 1-q
                    j = iq[i];
                    if (carry == 0) {
                        if (j != 0) {
                            carry = 1;
                            iq[i] = 0x100_0000 - j;
                        }
                    } else {
                        iq[i] = 0xff_ffff - j;
                    }
                }
                if (q0 > 0) {          // rare case: chance is 1 in 12
                    switch (q0) {
                        case 1:
                            iq[jz - 1] &= 0x7f_ffff;
                            break;
                        case 2:
                            iq[jz - 1] &= 0x3f_ffff;
                            break;
                    }
                }
                if (ih == 2) {
                    z = 1.0 - z;
                    if (carry != 0) {
                        z -= Math.scalb(1.0, q0);
                    }
                }
            }

            // check if recomputation is needed
            if (z == 0.0) {
                j = 0;
                for (i = jz - 1; i >= jk; i--) {
                    j |= iq[i];
                }
                if (j == 0) { // need recomputation
                    for (k = 1; iq[jk - k] == 0; k++) {
                        // k = no. of terms needed
                    }

                    for (i = jz + 1; i <= jz + k; i++) {   // add q[jz+1] to q[jz+k]
                        f[jx + i] = (double) TWO_OVER_PI[jv + i];
                        for (j = 0, fw = 0.0; j <= jx; j++) {
                            fw += x[j] * f[jx + i - j];
                        }
                        q[i] = fw;
                    }
                    jz += k;
                    continue;
                } else {
                    break;
                }
            } else {
                break;
            }
        }

        // chop off zero terms
        if (z == 0.0) {
            jz -= 1;
            q0 -= 24;
            while (iq[jz] == 0) {
                jz--;
                q0 -= 24;
            }
        } else { // break z into 24-bit if necessary
            z = Math.scalb(z, -q0);
            if (z >= TWO24) {
                fw = (double) ((int) (TWON24 * z));
                iq[jz] = (int) (z - TWO24 * fw);
                jz += 1;
                q0 += 24;
                iq[jz] = (int) fw;
            } else {
                iq[jz] = (int) z;
            }
        }

        // convert integer "bit" chunk to floating-point value
        fw = Math.scalb(1.0, q0);
        for (i = jz; i >= 0; i--) {
            q[i] = fw * (double) iq[i];
            fw *= TWON24;
        }

        // compute PIo2[0,...,jp]*q[jz,...,0]
        for (i = jz; i >= 0; i--) {
            for (fw = 0.0, k = 0; k <= jp && k <= jz - i; k++) {
                fw += PIO2[k] * q[i + k];
            }
            fq[jz - i] = fw;
        }

        // compress fq[] into y[] -- fdlibm's `case 1: case 2:` arm
        fw = 0.0;
        for (i = jz; i >= 0; i--) {
            fw += fq[i];
        }
        s.y0 = (ih == 0) ? fw : -fw;
        fw = fq[0] - fw;
        for (i = 1; i <= jz; i++) {
            fw += fq[i];
        }
        s.y1 = (ih == 0) ? fw : -fw;

        return n & 7;
    }
}
